---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

paths:
    cached_data: /data/scratch/weak_lensing/weak_lensing_img2048_constantshear
    output: /home/twhit/bliss/

prior:
    _target_: case_studies.weak_lensing.lensing_prior.LensingPrior
    n_tiles_h: 12  # cropping 2 tiles from each side (4 total)
    n_tiles_w: 12  # cropping 2 tiles from each side (4 total)
    batch_size: 2
    max_sources: 200
    shear_min: -0.1
    shear_max: 0.1
    convergence_min: -0.0001
    convergence_max: 0.0001
    prob_galaxy: 1.0
    mean_sources: 82  # 0.02 * (256/4) * (256/4)

decoder:
    _target_: case_studies.weak_lensing.lensing_decoder.LensingDecoder
    tile_slen: 256
    use_survey_background: false
    with_dither: false
    with_noise: false

cached_simulator:
    batch_size: 1
    train_transforms: []

variational_factors:
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: shear_1
    nll_gating: null
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: shear_2
    nll_gating: null

my_normalizers:
    nully:
        _target_: bliss.encoder.image_normalizer.NullNormalizer

my_metrics:
    lensing_map:
            _target_: case_studies.weak_lensing.lensing_metrics.LensingMapMSE

my_render:
    lensing_shear_conv:
        _target_: case_studies.weak_lensing.lensing_plots.PlotWeakLensingShearConvergence
        frequency: 1
        restrict_batch: 0
        save_local: ${paths.output}/${train.trainer.logger.name}/${train.trainer.logger.version}/lensing_maps

encoder:
    _target_: case_studies.weak_lensing.lensing_encoder.WeakLensingEncoder
    survey_bands: [u, g, r, i, z]
    reference_band: 2  # r-band
    tile_slen: 256
    n_tiles: 8
    nch_hidden: 64
    optimizer_params:
        lr: 1e-3
    scheduler_params:
        milestones: [32]
        gamma: 0.1
    image_normalizers: ${my_normalizers}
    var_dist:
        _target_: bliss.encoder.variational_dist.VariationalDist
        tile_slen: ${encoder.tile_slen}
        factors: ${variational_factors}
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_image_renders:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_render}
    use_double_detect: false
    use_checkerboard: false
    loss_plots_location: ${paths.output}/${train.trainer.logger.name}/${train.trainer.logger.version}/loss_plots

generate:
    n_image_files: 50
    n_batches_per_file: 4

train:
    trainer:
        logger:
            name: weak_lensing_experiments_simulator
            version: september24
        devices: 1
        use_distributed_sampler: false
        precision: 32-true
    data_source: ${cached_simulator}
    pretrained_weights: null
    seed: 123123
