---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

variational_factors:
  - _target_: bliss.encoder.variational_dist.BivariateNormalFactor
    name: shear
    sample_rearrange: "1 ht wt d -> 1 ht wt d"
    # nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
    nll_rearrange: "b ht wt d -> b ht wt d"
    nll_gating: null
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: convergence
    # sample_rearrange: "b ht wt -> b ht wt 1 1"
    # nll_rearrange: "b ht wt 1 1 -> b ht wt"
    sample_rearrange: "b ht wt -> b ht wt 1"
    nll_rearrange: "b ht wt 1 -> b ht wt"
    nll_gating: null

prior:
    _target_: case_studies.weak_lensing.lensing_prior.LensingPrior
    n_tiles_h: 16
    n_tiles_w: 16
    tile_slen: 256
    batch_size: 1
    prob_galaxy: 1.0
    mean_sources: 0.2
    arcsec_per_pixel: 0.0555
    sample_method: cosmology
    shear_mean: 0
    shear_std: 0.02
    convergence_mean: 0
    convergence_std: 0.02
    num_knots: 2

simulator:
    _target_: case_studies.weak_lensing.lensing_simulated_dataset.LensingSimulatedDataset

cached_simulator:
    cached_data_path: /data/scratch/shreyas/weak_lensing_cosmology_prior
    batch_size: 1
    splits: 0:80/80:90/90:100

encoder:
    _target_: case_studies.weak_lensing.lensing_encoder.WeakLensingEncoder
    tiles_to_crop: 0
    metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics:
            lensing_map:
                _target_: case_studies.weak_lensing.lensing_metrics.LensingMapMSE
    sample_image_renders:
        _target_: torchmetrics.MetricCollection
        metrics:
          - _target_: case_studies.weak_lensing.lensing_plots.PlotWeakLensingShearConvergence
            frequency: 1
            restrict_batch: 0
            tile_slen: ${simulator.prior.tile_slen}
    use_double_detect: false
    use_checkerboard: false

surveys:
    dc2:
        _target_: case_studies.weak_lensing.lensing_dc2.LensingDC2DataModule
        dc2_image_dir: ${paths.dc2}/run2.2i-dr6-v4/coadd-t3828-t3829/deepCoadd-results/
        dc2_cat_path: /data/scratch/shreyasc/lensing_catalog.pkl
        image_slen: 4096
        n_image_split: 1
        tile_slen: 256
        splits: 0:80/80:90/90:100
        batch_size: 1
        num_workers: 1
        cached_data_path: ${paths.output}/dc2_cached_data

train:
    trainer:
        logger:
            name: dc2_weak_lensing_exp
            version: exp_06-28_01
        devices: [1]
        use_distributed_sampler: false
    data_source: ${surveys.dc2}
    pretrained_weights: null
    seed: 123123
