---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

paths:
    dc2: /data/scratch/dc2local  # change for gl
    output: /data/scratch/shreyasc/bliss_output  # change for gl

prior:
    _target_: case_studies.weak_lensing.lensing_prior.LensingPrior
    star_color_model_path: /data/scratch/sdss/color_models/star_gmm_nmgy.pkl
    gal_color_model_path: /data/scratch/sdss/color_models/gal_gmm_nmgy.pkl
    n_tiles_h: 8
    n_tiles_w: 8
    batch_size: 1
    prob_galaxy: 1.0
    mean_sources: 162
    arcsec_per_pixel: 0.055
    sample_method: cosmology
    shear_mean: 0
    shear_std: 0.0175
    convergence_mean: 0
    convergence_std: 0.025
    num_knots: 4

decoder:
    _target_: case_studies.weak_lensing.lensing_decoder.LensingDecoder
    tile_slen: 128
    survey: ${surveys.sdss}

simulator:
    n_batches: 128
    num_workers: 32
    valid_n_batches: 10
    fix_validation_set: true

variational_factors:
  - _target_: bliss.encoder.variational_dist.BivariateNormalFactor
    name: shear
    nll_gating: null
#   - _target_: bliss.encoder.variational_dist.NormalFactor
#     name: convergence
#     nll_gating: null
#     high_clamp: 20.0
#     low_clamp: -20.0

my_normalizers:
    # asinh:
    #     _target_: bliss.encoder.image_normalizer.AsinhQuantileNormalizer
    #     q: [0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99, 0.999, 0.9999, 0.99999]
    #     sample_every_n: 4
    nully:
        _target_: bliss.encoder.image_normalizer.NullNormalizer

my_metrics:
    lensing_map:
            _target_: case_studies.weak_lensing.lensing_metrics.LensingMapMSE

my_render:
    lensing_shear_conv:
        _target_: case_studies.weak_lensing.lensing_plots.PlotWeakLensingShearConvergence
        frequency: 1
        restrict_batch: 0
        tile_slen: 256
        save_local: "lensing_maps"

encoder:
    _target_: case_studies.weak_lensing.lensing_encoder.WeakLensingEncoder
    survey_bands: ["u", "g", "r", "i", "z", "y"]
    reference_band: 2  # r-band
    tile_slen: 256
    n_tiles: 8
    nch_hidden: 64
    optimizer_params:
        lr: 1e-3
    scheduler_params:
        milestones: [32]
        gamma: 0.1
    image_normalizers: ${my_normalizers}

    var_dist:
        _target_: bliss.encoder.variational_dist.VariationalDist
        tile_slen: ${encoder.tile_slen}
        factors: ${variational_factors}
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_image_renders:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_render}
    use_double_detect: false
    use_checkerboard: false
    train_loss_location: "train_loss_plt"

surveys:
    dc2:
        _target_: case_studies.weak_lensing.lensing_dc2.LensingDC2DataModule
        dc2_image_dir: ${paths.dc2}/run2.2i-dr6-v4/coadd-t3828-t3829/deepCoadd-results/
        dc2_cat_path: ${paths.dc2}/dc2_lensing_catalog.pkl
        image_slen: 4096
        n_image_split: 2  # split into n_image_split**2 subimages
        tile_slen: 256
        splits: 0:80/80:90/90:100
        batch_size: 1
        num_workers: 1
        cached_data_path: ${paths.dc2}/dc2_lensing_splits_img2048_tile256

train:
    trainer:
        logger:
            name: dc2_weak_lensing_exp
            version: exp_08_12
        devices: [0] # cuda:0 for gl
        use_distributed_sampler: false
        precision: 32-true
    data_source: ${surveys.dc2}
    pretrained_weights: null
    seed: 123123
