---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    root: ${oc.env:BLISS_HOME}
    data: ${paths.root}/data

prior:
    _target_: case_studies.weak_lensing.lensing_prior.LensingPrior
    n_tiles_h: 20
    n_tiles_w: 20
    tile_slen: 4
    batch_size: 32
    prob_galaxy: 1.0
    shear_min: -0.1
    shear_max: 0.1
    convergence_a: 1
    convergence_b: 25

simulator:
    _target_: case_studies.weak_lensing.lensing_simulated_dataset.LensingSimulatedDataset

generate:
    n_image_files: 16
    n_batches_per_file: 16
    cached_data_path: ${paths.data}/scratch/weak_lensing

cached_simulator:
    cached_data_path: ${paths.data}/scratch/weak_lensing
    batch_size: 32

encoder:
    metrics:
        _target_: torchmetrics.MetricCollection
        metrics:
          - _target_: bliss.encoder.metrics.DetectionPerformance
            mag_bin_cutoffs: [19, 19.4, 19.8, 20.2, 20.6, 21, 21.4, 21.8, 22.065]
            exclude_last_bin: true
    vd_spec:
        _target_: case_studies.weak_lensing.lensing_variational_dist.LensingVariationalDistSpec
    double_detect: false
    use_checkerboard: false
