---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

paths:
    dc2: /data/scratch/dc2local
    output: /home/twhit/bliss/

variational_factors:
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: shear_1
    nll_gating: null
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: shear_2
    nll_gating: null
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: convergence
    nll_gating: null

my_normalizers:
    nullnorm:
        _target_: bliss.encoder.image_normalizer.NullNormalizer

my_metrics:
    lensing_map:
            _target_: case_studies.weak_lensing.lensing_metrics.LensingMSE

my_render:
    lensing_shear_conv:
        _target_: case_studies.weak_lensing.lensing_plots.PlotLensingMaps
        frequency: 1
        save_local: ${paths.output}/${train.trainer.logger.name}/${train.trainer.logger.version}/lensing_maps

encoder:
    _target_: case_studies.weak_lensing.lensing_encoder.WeakLensingEncoder
    survey_bands: ["u", "g", "r", "i", "z", "y"]
    reference_band: 2  # r-band
    tile_slen: 256
    n_tiles: 8
    nch_hidden: 64
    optimizer_params:
        lr: 1e-3
    scheduler_params:
        milestones: [32]
        gamma: 0.1
    image_normalizers: ${my_normalizers}
    var_dist:
        _target_: bliss.encoder.variational_dist.VariationalDist
        tile_slen: ${encoder.tile_slen}
        factors: ${variational_factors}
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_image_renders:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_render}
    use_double_detect: false
    use_checkerboard: false
    loss_plots_location: ${paths.output}/${train.trainer.logger.name}/${train.trainer.logger.version}/loss_plots

surveys:
    dc2:
        _target_: case_studies.weak_lensing.lensing_dc2.LensingDC2DataModule
        dc2_image_dir: /data/scratch/dc2_nfs/run2.2i-dr6-v4/coadd-t3828-t3829/deepCoadd-results/
        dc2_cat_path: ${paths.dc2}/dc2_lensing_catalog.pkl
        image_slen: 4096
        n_image_split: 2  # split into n_image_split**2 subimages
        tile_slen: 256
        splits: 0:80/80:90/90:100
        avg_ellip_kernel_size: 15  # must be odd
        avg_ellip_kernel_sigma: 15
        redshift_quantiles: [0.00]
        num_redshift_bins: 1  # length of redshift_quantiles
        batch_size: 1
        num_workers: 1
        cached_data_path: ${paths.dc2}/dc2_lensing_splits
        train_transforms:
            - _target_: case_studies.weak_lensing.lensing_data_augmentation.LensingRotateFlipTransform
        shuffle_file_order: false  # partition train/val/test by ra/dec so that we can compute 2PCFs on spatially contiguous test set

train:
    trainer:
        logger:
            name: weak_lensing_experiments_dc2
            version: may16
        max_epochs: 250
        devices: 1
        use_distributed_sampler: false
        precision: 32-true
    callbacks:
        early_stopping:
            patience: 100
    data_source: ${surveys.dc2}
    pretrained_weights: null
    seed: 123123
