---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    root: ${oc.env:BLISS_HOME}
    data: ${paths.root}/data
    sdss: ${paths.data}/sdss

prior:
    _target_: case_studies.weak_lensing.lensing_prior.LensingPrior
    n_tiles_h: 20
    n_tiles_w: 20
    tile_slen: 4
    batch_size: 32
    prob_galaxy: 1.0
    shear_min: -0.5
    shear_max: 0.5
    convergence_a: 1
    convergence_b: 10

simulator:
    _target_: case_studies.weak_lensing.lensing_simulated_dataset.LensingSimulatedDataset

generate:
    n_image_files: 16
    n_batches_per_file: 16
    cached_data_path: /data/scratch/twhit/weak_lensing_new

cached_simulator:
    cached_data_path: /data/scratch/twhit/weak_lensing_new
    batch_size: 24

encoder:
    metrics:
        _target_: torchmetrics.MetricCollection
        metrics:
          - _target_: bliss.encoder.metrics.DetectionPerformance
            mag_bin_cutoffs: [19, 19.4, 19.8, 20.2, 20.6, 21, 21.4, 21.8, 22.065]
            exclude_last_bin: true
    vd_spec:
        _target_: case_studies.weak_lensing.lensing_variational_dist.LensingVariationalDistSpec
    double_detect: false
    use_checkerboard: true

surveys:
    sdss:
        _target_: bliss.surveys.sdss.SloanDigitalSkySurvey
        dir_path: ${paths.sdss}
        fields:  # TODO: better arbitary name for fields/bricks?
            - run: 2334
              camcol: 6
              fields: [13]
        psf_config:
            pixel_scale: 0.396
            psf_slen: 25
        pixel_shift: 2
        align_to_band: null
        load_image_data: true
