---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

paths:
    dc2: /data/scratch/dc2local
    cached_data: /data/scratch/weak_lensing
    output: /data/scratch/twhit/bliss_output

prior:
    _target_: case_studies.weak_lensing.lensing_prior.LensingPrior
    n_tiles_h: 130
    n_tiles_w: 130
    constant_shear: 0.2
    constant_convergence: 0.2
    prob_galaxy: 1.0
    mean_sources: 0.02

decoder:
    _target_: case_studies.weak_lensing.lensing_decoder.LensingDecoder
    with_dither: false
    with_noise: false

simulator:
    n_batches: 128
    num_workers: 32
    valid_n_batches: 10
    fix_validation_set: true

variational_factors:
  - _target_: bliss.encoder.variational_dist.BivariateNormalFactor
    name: shear
    nll_gating: null
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: convergence
    nll_gating: null
    high_clamp: 20.0
    low_clamp: -20.0

my_normalizers:
    # asinh:
    #     _target_: bliss.encoder.image_normalizer.AsinhQuantileNormalizer
    #     q: [0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99, 0.999, 0.9999, 0.99999]
    #     stride: 4
    nully:
        _target_: bliss.encoder.image_normalizer.NullNormalizer

my_metrics:
    lensing_map:
            _target_: case_studies.weak_lensing.lensing_metrics.LensingMapMSE

my_render:
    lensing_shear_conv:
        _target_: case_studies.weak_lensing.lensing_plots.PlotWeakLensingShearConvergence
        frequency: 1
        restrict_batch: 0
        tile_slen: 256
        save_local: "lensing_maps"

encoder:
    _target_: case_studies.weak_lensing.lensing_encoder.WeakLensingEncoder
    survey_bands: ["u", "g", "r", "i", "z", "y"]
    reference_band: 2  # r-band
    tile_slen: 256
    optimizer_params:
        lr: 1e-3
    scheduler_params:
        milestones: [32]
        gamma: 0.1
    image_normalizers: ${my_normalizers}

    var_dist:
        _target_: bliss.encoder.variational_dist.VariationalDist
        tile_slen: ${encoder.tile_slen}
        factors: ${variational_factors}
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_image_renders:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_render}
    use_double_detect: false
    use_checkerboard: false
    train_loss_location: "train_loss_plt"

surveys:
    dc2:
        _target_: case_studies.weak_lensing.lensing_dc2.LensingDC2DataModule
        dc2_image_dir: ${paths.dc2}/run2.2i-dr6-v4/coadd-t3828-t3829/deepCoadd-results/
        dc2_cat_path: ${paths.dc2}/dc2_lensing_catalog.pkl
        image_slen: 4096
        n_image_split: 2  # split into n_image_split**2 subimages
        tile_slen: 256
        splits: 0:80/80:90/90:100
        avg_ellip_kernel_size: 7  # needs to be odd
        avg_ellip_kernel_sigma: 3
        batch_size: 1
        num_workers: 1
        cached_data_path: ${paths.dc2}/dc2_lensing_splits_img2048_tile256

generate:
  n_batches_per_file: 4
