---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

paths:
    cached_data: /data/scratch/weak_lensing/weak_lensing_img2048_meta_varying_shear
    output: /home/twhit/bliss/

cached_simulator:
    batch_size: 1
    train_transforms: []

variational_factors:
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: shear_1
    nll_gating: null
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: shear_2
    nll_gating: null

my_normalizers:
    nullnorm:
        _target_: bliss.encoder.image_normalizer.NullNormalizer

my_metrics:
    lensing_map:
            _target_: case_studies.weak_lensing.lensing_metrics.LensingMSE

my_render:
    lensing_shear_conv:
        _target_: case_studies.weak_lensing.lensing_plots.PlotLensingMaps
        frequency: 1
        save_local: ${paths.output}/${train.trainer.logger.name}/${train.trainer.logger.version}/lensing_maps

encoder:
    _target_: case_studies.weak_lensing.lensing_encoder.WeakLensingEncoder
    survey_bands: [i]
    reference_band: 0
    tile_slen: 256
    n_tiles: 8
    nch_hidden: 64
    optimizer_params:
        lr: 1e-3
    scheduler_params:
        milestones: [32]
        gamma: 0.1
    image_normalizers: ${my_normalizers}
    var_dist:
        _target_: bliss.encoder.variational_dist.VariationalDist
        tile_slen: ${encoder.tile_slen}
        factors: ${variational_factors}
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_metrics}
    sample_image_renders:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${my_render}
    use_double_detect: false
    use_checkerboard: false
    loss_plots_location: ${paths.output}/${train.trainer.logger.name}/${train.trainer.logger.version}/loss_plots

train:
    trainer:
        logger:
            name: weak_lensing_experiments_descwl
            version: may21
        max_epochs: 250
        devices: 1
        use_distributed_sampler: false
        precision: 32-true
    callbacks:
        early_stopping:
            patience: 100
    data_source: ${cached_simulator}
    pretrained_weights: null
    seed: 123123
