---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    root: ${oc.env:BLISS_HOME}
    data: ${paths.root}/data

prior:
    _target_: case_studies.weak_lensing.lensing_prior.LensingPrior
    n_tiles_h: 20
    n_tiles_w: 20
    tile_slen: 4
    batch_size: 32
    prob_galaxy: 1.0
    shear_min: -0.1
    shear_max: 0.1
    convergence_a: 1
    convergence_b: 25

simulator:
    _target_: case_studies.weak_lensing.lensing_simulated_dataset.LensingSimulatedDataset

generate:
    n_image_files: 4
    n_batches_per_file: 8
    cached_data_path: ${paths.data}/scratch/cached_dataset

cached_simulator:
    cached_data_path: ${paths.data}/scratch/cached_dataset
    batch_size: 32

encoder:
    vd_spec:
        _target_: case_studies.weak_lensing.lensing_variational_dist.LensingVariationalDistSpec
