_target_: bliss.models.decoder.ImageDecoder
n_bands: 1
slen: 40
tile_slen: 4
ptile_slen: 52
border_padding: 4
prob_galaxy: 0.5
n_galaxy_params: 8
max_sources: 1
mean_sources: 0.035
min_sources: 0
gal_slen: 53
autoencoder_ckpt: ${paths.models}/sdss_autoencoder.ckpt
latents_file: ${paths.data}/latents_simulated_sdss_galaxies.pt
psf_params_file: ${paths.root}/data/fitted_powerlaw_psf_params.npy
background_values:
  - 633.0
