n_bands: 1
slen: 40
tile_slen: 4
ptile_slen: 52
border_padding: 4
prob_galaxy: 0.5
autoencoder_ckpt: models/sdss_autoencoder.ckpt
psf_params_file: data/sdss/94/1/12/psField-000094-1-0012.fits
background_values:
  - 633.0
