n_bands: 1
slen: 40
tile_slen: 4
max_sources: 1
mean_sources: 0.03
min_sources: 0
f_min: 1e3
f_max: 1e6
alpha: 0.5
prob_galaxy: 0.7
autoencoder_ckpt: models/sdss_autoencoder.ckpt
latents_file: data/latents_simulated_sdss_galaxies.pt

