---
defaults:
    - ../../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    cached_data: /data/scratch/regier/sdss_like

encoder:
    use_checkerboard: true

train:
    trainer:
        logger:
            name: sdsslike

predict:
    dataset:
        load_image_data: true

surveys:
    sdss:
        fields:
            - run: 94
              camcol: 1
              fields: [12]
