# @package _global_
training:
  name: "galaxy_encoder"
  model: ${models.galaxy_encoder}
  dataset: ${datasets.simulated}
  optimizer_params:
    lr: 1e-4
  n_epochs: 3501
  trainer:
    enable_checkpointing: True
    check_val_every_n_epoch: 50
