defaults:
  - _self_
  - override hydra/job_logging: stdout

# completely disable hydra logging
# https://github.com/facebookresearch/hydra/issues/910
hydra:
  output_subdir: null
  run:
    dir: .

mode: train

gpus: 1 # use a single gpu by default.

paths:
  root:
  output: ${paths.root}/output
  sdss: ${paths.root}/data/sdss
  data: ${paths.root}/data

datasets:
  simulated_m2:
    _target_: bliss.datasets.simulated.SimulatedDataset
    prior: ${models.prior}
    decoder: ${models.decoder}
    background:
      - 667.0
      - 496.0
    n_batches: 40
    batch_size: 4
    generate_device: "cuda:0"
    testing_file: null

models:
  decoder:
    _target_: bliss.models.decoder.ImageDecoder
    n_bands: 2
    tile_slen: 10
    ptile_slen: 30
    border_padding: 5
    psf_params_file: ./../../../data/sdss/2583/2/136/psField-002583-2-0136.fits
    sdss_bands:
      - 2
      - 3
  encoder:
    _target_: bliss.models.location_encoder.LocationEncoder
    n_bands: ${models.decoder.n_bands}
    tile_slen: ${models.decoder.tile_slen}
    ptile_slen: 20
    max_detections: 3
    channel: 17
    spatial_dropout: 0.11399
    dropout: 0.013123
    hidden: 185
  prior:
    _target_: bliss.models.prior.ImagePrior
    n_bands: 2
    slen: 300
    tile_slen: 10
    max_sources: 3
    mean_sources: 0.48
    min_sources: 0
    f_min: 1e3
    f_max: 1e6
    alpha: 0.5
    prob_galaxy: 0.0
  sleep:
    _target_: bliss.sleep.SleepPhase
    encoder: ${models.encoder}
    decoder: ${models.decoder}

training:
  model: "${models.sleep}"
  dataset: "${datasets.simulated_m2}"
  optimizer_params:
    lr: 0.00098352
    weight_decay: 0.000080410
  n_epochs: 100
  experiment: default
  version: null
  save_top_k: 1
  trainer:
    _target_: pytorch_lightning.Trainer
    logger: False
    enable_checkpointing: False
    profiler: null
    reload_dataloaders_every_epoch: False
    check_val_every_n_epoch: 50
    max_epochs: ${training.n_epochs}
    min_epochs: ${training.n_epochs}
    gpus: ${gpus}
    log_every_n_steps: 10
    deterministic: False
  weight_save_path: Null
