---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

surveys:
  dc2:
    batch_size: 32
    tile_slen: 0.5
    max_sources_per_tile: 2
    cached_data_path: ${paths.output}/dc2_cached_data_half_pixel
    store_sparse_tensor: true
    num_workers: 16
    train_transforms:
      - _target_: bliss.data_augmentation.RotateFlipTransform
      - _target_: case_studies.dc2_diffusion.utils.data_augmentation.HalfPixelRandomShiftTransform
        tile_slen: ${surveys.dc2.tile_slen}
        max_sources_per_tile: 4
      - _target_: bliss.cached_dataset.FluxFilterTransform
        reference_band: 2  # r-band
        min_flux: 100

my_diffusion_factors:
  - _target_: case_studies.dc2_diffusion.utils.catalog_parser.OneBitNSourcesLocsFactor
    n_params: 1
    name: n_sources
    bit_value: 0.8
    sample_rearrange: b ht wt 1 -> b ht wt
    loss_gating:
      _target_: case_studies.dc2_diffusion.utils.catalog_parser.WeightedNSourcesGating
  - _target_: case_studies.dc2_diffusion.utils.catalog_parser.OneBitFactor
    n_params: 1
    name: source_type
    bit_value: 0.8
    sample_rearrange: b ht wt 1 -> b ht wt 1 1
    loss_gating:
      _target_: case_studies.dc2_diffusion.utils.catalog_parser.SourcesGating

my_metrics:
  detection_performance:
    _target_: case_studies.dc2_diffusion.utils.metrics.DetectionPerformance
  detection_performance_star:
    _target_: case_studies.dc2_diffusion.utils.metrics.DetectionPerformance
    filter_list:
      - _target_: bliss.encoder.metrics.SourceTypeFilter
        filter_type: star
  detection_performance_galaxy:
    _target_: case_studies.dc2_diffusion.utils.metrics.DetectionPerformance
    filter_list:
      - _target_: bliss.encoder.metrics.SourceTypeFilter
        filter_type: galaxy
  source_type_accuracy:
    _target_: bliss.encoder.metrics.SourceTypeAccuracy
    base_flux_bin_cutoffs: [200, 400, 600, 800, 1000]
    mag_zero_point: 3631e9  # for DC2
    report_bin_unit: mag

my_image_normalizers:
  null_noramlize:
      _target_: case_studies.dc2_cataloging.utils.image_normalizer.NullNormalizer

encoder:
    _target_: case_studies.dc2_diffusion.utils.half_pixel_encoder.HalfPixelDiffusionEncoder
    survey_bands: [u, g, r, i, z, y]
    reference_band: 2
    tile_slen: ${surveys.dc2.tile_slen}
    ddim_steps: 50
    ddim_objective: pred_x0
    ddim_beta_schedule: sigmoid
    ddim_self_cond: false
    optimizer_params:
        lr: 1e-3
    scheduler_params:
        milestones: [32]
        gamma: 0.1
    image_normalizers: ${my_image_normalizers}
    catalog_parser:
        _target_: case_studies.dc2_diffusion.utils.catalog_parser.CatalogParser
        factors: ${my_diffusion_factors}
    image_size: [80, 80]
    matcher:
        _target_: bliss.encoder.metrics.CatalogMatcher
        dist_slack: 1.0
        mag_slack: null
        mag_band: 2  # SDSS r-band
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        compute_groups: false
        metrics: ${my_metrics}

train:
    trainer:
        logger:
            name: DC2_diffusion_exp
            version: exp_01-15-5  # change it before running the code
        devices: [3]  # change it before running the code
        use_distributed_sampler: false  # disable this because we use the self-defined distributed sampler
        precision: 32-true
    data_source: ${surveys.dc2}
    pretrained_weights: null
    seed: 7272
