# @package _global_
models:
  prior:
    mean_sources: 0.03

training:
  name: "sdss_binary"
  model: ${models.binary}
  dataset: ${datasets.simulated}
  n_epochs: 501
  save_top_k: 5
  trainer:
    enable_checkpointing: True
