# @package _global_
dataset:
  prerender_device: "cuda"

models:
  galaxy_encoder:
    crop_loss_at_border: True
    checkpoint_path: "${paths.project}/models/sdss_galaxy_encoder.pt"
    max_flux_valid_plots: 1200
  prior:
    mean_sources: 0.04

training:
  name: "sdss_galaxy_encoder_real"
  model: ${models.galaxy_encoder}
  dataset: ${datasets.sdss_blended_galaxies}
  optimizer_params:
    lr: 1e-4
  n_epochs: 160
  trainer:
    enable_checkpointing: True
    check_val_every_n_epoch: 1
