name: BinaryEncoder
kwargs:
  n_bands: 1
  tile_slen: 4
  ptile_slen: 52
  channel: 8
  hidden: 128
  spatial_dropout: 0.0
  dropout: 0.0
  optimizer_params: ${optimizer}
decoder: # SDSS standard decoder.
  kwargs:
    n_bands: 1
    slen: 40
    tile_slen: 4
    ptile_slen: 52
    border_padding: 24
    max_sources: 1
    mean_sources: 0.03
    min_sources: 0
    f_min: 1e3
    f_max: 1e6
    alpha: 0.5
    psf_params_file: ${paths.data}/psField-000094-1-0012.fits
    prob_galaxy: 0.7
    n_galaxy_params: 8
    gal_slen: 53
    autoencoder_ckpt: ${paths.models}/sdss_autoencoder.ckpt
    latents_file: ${paths.data}/latents_simulated_sdss_galaxies.pt
    background_values:
      - 865.0
    sdss_bands:
      - 2
