name: GalaxyEncoder
kwargs:
  hidden: 256
  decoder_kwargs: ${model.decoder.kwargs}
  optimizer_params: ${optimizer}
decoder:
  kwargs:
    n_bands: 1
    slen: 4
    tile_slen: 4
    ptile_slen: 52
    border_padding: 24
    max_sources: 1
    mean_sources: 1
    min_sources: 1
    prob_galaxy: 1.0
    n_galaxy_params: 8
    gal_slen: 53
    autoencoder_ckpt: ${paths.models}/gaussian_ae.ckpt
    latents_file: ${paths.data}/latents_simulated_gaussian_galaxies.pt
    psf_params_file: ${paths.root}/data/fitted_powerlaw_psf_params.npy
    background_values:
      - 865.0
