name: SleepPhase
kwargs:
  decoder_kwargs: ${model.decoder.kwargs}
  encoder_kwargs: ${model.encoder.kwargs}
  optimizer_params: ${optimizer}
  annotate_probs: True
decoder:
  kwargs:
    n_bands: 1
    slen: 40
    tile_slen: 4
    ptile_slen: 52
    border_padding: 24
    prob_galaxy: 0.7
    n_galaxy_params: 8
    max_sources: 1
    mean_sources: 0.03
    min_sources: 0
    f_min: 1e3
    f_max: 1e6
    alpha: 0.5
    gal_slen: 53
    autoencoder_ckpt: ${paths.models}/sdss_autoencoder.ckpt
    latents_file: ${paths.data}/latents_simulated_sdss_galaxies.pt
    psf_params_file: ${paths.root}/data/psField-000094-1-0012.fits
    psf_file: Null
    background_values:
      - 865.0
    sdss_bands:
      - 2
encoder:
  kwargs:
    n_bands: ${model.decoder.kwargs.n_bands}
    tile_slen: ${model.decoder.kwargs.tile_slen}
    ptile_slen: 52
    max_detections: ${model.decoder.kwargs.max_sources}
    channel: 8
    spatial_dropout: 0.0
    dropout: 0.0
    hidden: 128
