name: SleepPhase
image:
  slen: 10
  n_bands: 1
  background:
    - 633.0
kwargs:
  decoder_kwargs:
    n_bands: ${model.image.n_bands}
    slen: ${model.image.slen}
    tile_slen: ${model.image.slen}
    ptile_slen: ${model.image.slen}
    prob_galaxy: 0.0
    max_sources: 2
    mean_sources: 1.2
    min_sources: 0
    f_min: 1e5
    f_max: 1e6
    psf_params_file: ${paths.root}/data/fitted_powerlaw_psf_params.npy
    background_values: ${model.image.background}
    loc_min: 0.
    loc_max: 1.0
  encoder_kwargs:
    n_bands: ${model.image.n_bands}
    tile_slen: ${model.kwargs.decoder_kwargs.tile_slen}
    ptile_slen: ${model.kwargs.decoder_kwargs.tile_slen}
    max_detections: ${model.kwargs.decoder_kwargs.max_sources}
    channel: 17
    spatial_dropout: 0.11399
    dropout: 0.013123
    hidden: 185
  use_galaxy_encoder: False
