# @package _group_
image:
  slen: 10
decoder:
  params:
    tile_slen: ${model.image.slen}
    ptile_slen: ${model.image.slen}
    max_sources: 2
    mean_sources: 1.2
    loc_min: 0.
    loc_max: 1.0
encoder:
  params:
    ptile_slen: ${model.decoder.params.tile_slen}
    enc_conv_c: 20
    enc_kern: 3
    enc_hidden: 256
