name: SleepPhase
kwargs:
  decoder_kwargs: ${model.decoder.kwargs}
  encoder_kwargs: ${model.encoder.kwargs}
  optimizer_params: ${optimizer}
decoder:
  kwargs:
    n_bands: 2
    slen: 100
    tile_slen: 2
    ptile_slen: 26
    border_padding: 3
    max_sources: 5
    mean_sources: 0.48
    min_sources: 0
    f_min: 1e3
    f_max: 1e6
    alpha: 0.5
    psf_params_file: ${paths.root}/data/psField-002583-2-0136.fits
    prob_galaxy: 0.0
    background_values:
      - 686.0
      - 1123.0
    sdss_bands:
      - 2
      - 3
encoder:
  kwargs:
    n_bands: ${model.decoder.kwargs.n_bands}
    tile_slen: ${model.decoder.kwargs.tile_slen}
    ptile_slen: 8
    max_detections: 2
    channel: 17
    spatial_dropout: 0.11399
    dropout: 0.013123
    hidden: 185
