# @package _group_
name: SleepPhase
image:
  slen: 100
  n_bands: 2
  background:
    - 686.0
    - 1123.0
galaxy:
  slen: 51
  latent_dim: 8
decoder:
  n_bands: ${model.image.n_bands}
  slen: ${model.image.slen}
  tile_slen: 2
  ptile_padding: 1
  prob_galaxy: 0.0
  n_galaxy_params: ${model.galaxy.latent_dim}
  max_sources: 2
  mean_sources: 0.48
  min_sources: 0
  f_min: 1e3
  f_max: 1e6
  alpha: 0.5
  gal_slen: ${model.galaxy.slen}
  decoder_file:
  psf_params_file: ${paths.root}/data/psField-002583-2-0136.fits
  background_value: ${model.image.background}
encoder:
  n_bands: ${model.image.n_bands}
  slen: ${model.image.slen}
  tile_slen: ${model.decoder.tile_slen}
  ptile_slen: 8
  max_detections: ${model.decoder.max_sources}
  n_galaxy_params: ${model.galaxy.latent_dim}
  background_pad_value: ${model.image.background.0}
