---
defaults:
    - ..@_here_: redshift_continuous
    - _self_
    # - override hydra/job_logging: stdout

paths:
    ckpt_dir: ${paths.data_dir}/checkpoints/continuous_split_0_2025-04-18-14-39-44/checkpoints
    plot_dir: ${paths.data_dir}/plots

# To reduce memory usage
surveys:
    dc2:
        batch_size: 4
        max_sources_per_tile: 5
