---
defaults:
    - ..@_here_: redshift_discrete
    - _self_
    # - override hydra/job_logging: stdout

paths:
    ckpt_dir: ${paths.data_dir}/checkpoints/discrete_split_0_2025-04-22-09-50-08/checkpoints
    plot_dir: ${paths.data_dir}/plots

# To reduce memory usage
surveys:
    dc2:
        batch_size: 32
        max_sources_per_tile: 5
