ignore:
  - "bliss/main.py" # don't need to test hydra CLI wrapper
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        informational: true
comment:
  after_n_builds: 1
