repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: trailing-whitespace-fixer
        language: python
        exclude: ^(.*fits|.*pt|.*pkl|.*npz|.*ckpt|.*png|.*inv|.*npy|.*pdf|.*jpg)
      - id: check-added-large-files
        name: check-added-large-files
        entry: check-added-large-files
        language: python
        args:
          - "--maxkb=15000"
      - id: check-merge-conflict
        name: check-merge-conflict
        entry: check-merge-conflict
        language: python
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: python
        exclude: ^(.*fits|.*pt|.*pkl|.*npz|.*ckpt|.*png|.*inv|.*npy|.*pdf|.*jpg)
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
      - id: ruff-lint
        name: ruff lint
        entry: ruff check --fix
        language: system
        types: [python]
