ckpt: /scratch/regier_root/regier0/taodingr/bliss/WeakLensingResultsDescwl/WLD_80_star_80_vary_psf_1_with_filter_2025-07-22_23-24/checkpoints/encoder_288.ckpt
setting: WLD_80_star_80_vary_psf_1_with_filter