---
defaults:
    - full_train_config
    - _self_
    - override hydra/job_logging: stdout

encoder:
    tiles_to_crop: 0

surveys:
    dc2:
        cat_path: ${paths.root}/case_studies/dc2/merged_catalog/merged_catalog_with_flux_over_100.pkl
        # split_results_dir: /data/scratch/dc2local/run2.2i-dr6-v4/coadd-t3828-t3829/deepCoadd-results-contain-redshifts/
        split_results_dir: ${paths.root}/case_studies/redshift/redshift_from_img/DC2_split_result
