outdir: ${paths.output}/semisynthetic_figures
real: False
frame:
    _target_: bliss.inference.SemiSyntheticFrame
    dataset: ${datasets.simulated}
    coadd: ${paths.data}/coadd_catalog_94_1_12.fits
    n_tiles_h: 360
    n_tiles_w: 500
    cache_dir: ${reconstruct.outdir}
scenes:
    sdss_recon0:
        h: 200 #200
        w: 1700 #1700
        size: 300
    # sdss_recon1:
    #     h: 1174 #1150
    #     w: 1024 #1000
    #     size: 300
    sdss_recon2:
      h: 484 #460
      w: 766 #742
      size: 300
    sdss_recon4_star_galaxy:
      h: 581 #557
      w: 432 #408
      size: 300
    sdss_recon_all:
        h: 48 #24
        w: 48 #24
        size: "all"
