outdir: ${paths.output}/semisynthetic_figures
real: False
frame:
    _target_: bliss.inference.SemiSyntheticFrame
    dataset: ${datasets.simulated}
    coadd: ${paths.data}/coadd_catalog_94_1_12.fits
    n_tiles_h: 350
    n_tiles_w: 500
    cache_dir: ${reconstruct.outdir}
scenes:
    sdss_recon1:
        h: 1000
        w: 1000
        size: 300
    sdss_recon_all:
        h: 24
        w: 24
        size: "all"
