outdir: ${paths.output}/simulated_figures
real: False
frame:
    _target_: reconstruction.SimulatedFrame
    dataset: ${datasets.simulated}
    n_tiles_h: 350
    n_tiles_w: 500
    cache_dir: ${reconstruct.outdir}
scenes:
    recon1:
        h: 1000
        w: 1000
        size: 300
