defaults:
    - _self_
    - training: sdss_detection_encoder_full_decoder_coadd
    - override hydra/job_logging: stdout

# completely disable hydra logging
# https://github.com/facebookresearch/hydra/issues/910
hydra:
    output_subdir: null
    run:
        dir: .

mode: train

gpus: 1 # use a single gpu by default.

paths:
    root: ${oc.env:BLISS_HOME}
    sdss: ${paths.root}/data/sdss
    data: ${paths.root}/data
    project: ${paths.root}/case_studies/coadds
    output: ${paths.project}/output

datasets:
    sdss_galaxies:
        _target_: bliss.datasets.galsim_galaxies.SingleGalsimGalaxies
        prior:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyPrior
            flux_sample: "pareto"
            min_flux: 622.0
            max_flux: 1e6
            alpha: 0.47
            a_sample: "gamma"
            a_concentration: 0.39330758068481686
            a_loc: 0.8371888967872619
            a_scale: 4.432725319432478
            a_bulge_disk_ratio: 2.0
        decoder:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyDecoder
            n_bands: 1
            slen: 53
            pixel_scale: 0.396
            psf_image_file: ${paths.sdss}/psField-000094-1-0012-PSF-image.npy
        background:
            _target_: bliss.datasets.background.ConstantBackground
            background:
                - 865.0
        num_workers: 0
        batch_size: 256
        n_batches: 10
        fix_validation_set: True
        valid_n_batches: 200
    galsim_blended_galaxies:
        _target_: case_studies.coadds.coadd_decoder.CoaddGalsimBlends
        prior:
            _target_: bliss.models.galsim_decoder.UniformGalsimGalaxiesPrior
            single_galaxy_prior: ${datasets.sdss_galaxies.prior}
            max_n_sources: 6
            max_shift: 0.5
        decoder:
            _target_: case_studies.coadds.coadd_decoder.FullCatalogDecoder
            single_galaxy_decoder: ${datasets.sdss_galaxies.decoder}
            slen: 40
            bp: 24
        background: ${datasets.sdss_galaxies.background}
        tile_slen: 4
        max_sources_per_tile: 1
        num_workers: 10
        batch_size: 32
        n_batches: 10
        fix_validation_set: True
        valid_n_batches: 50
models:
    detection_encoder:
        _target_: bliss.models.detection_encoder.DetectionEncoder
        input_transform:
            _target_: bliss.models.detection_encoder.ConcatBackgroundTransform
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        mean_detections: 0.03
        max_detections: 1
        channel: 8
        spatial_dropout: 0.0
        dropout: 0.0
        hidden: 128
        annotate_probs: True
        slack: 1.0

generate:
    dataset:
    file:
    n_plots:

training:
    n_epochs: 121
    experiment: default
    version: null
    save_top_k: 1
    trainer:
        _target_: pytorch_lightning.Trainer
        logger: True
        enable_checkpointing: False
        profiler: null
        reload_dataloaders_every_n_epochs: 0
        max_epochs: ${training.n_epochs}
        min_epochs: ${training.n_epochs}
        gpus: ${gpus}
        limit_train_batches: 1.0
        limit_val_batches: 1.0
        check_val_every_n_epoch: 10
        log_every_n_steps: 10 # correspond to n_batches
    testing:
        file: null
        batch_size: 32
        num_workers: 0
    weight_save_path: ${paths.project}/models/${training.name}.pt
    seed: 42

plots:
    