trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: /home/yolandz/bliss/redshift_output
    name: null
    version: null
    default_hp_metric: false
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    filename: best_encoder
    save_top_k: 1
    verbose: true
    monitor: val/_loss
    mode: min
    save_on_train_epoch_end: false
    auto_insert_metric_name: false
  - _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    monitor: val/_loss
    mode: min
    patience: 5
  reload_dataloaders_every_n_epochs: 0
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  min_epochs: 1
  max_epochs: 50
  accelerator: gpu
  devices: 1
  precision: 32
data_source:
  _target_: bliss.simulator.simulated_dataset.CachedSimulatedDataset
  batch_size: 32
  splits: 0:80/80:90/90:100
  num_workers: 0
  cached_data_path: /data/scratch/declan/redshift_estimation_test
  file_prefix: dataset
encoder:
  _target_: bliss.encoder.encoder.Encoder
  survey_bands:
  - u
  - g
  - r
  - i
  - z
  tile_slen: 4
  tiles_to_crop: 1
  min_flux_threshold: 0
  optimizer_params:
    lr: 0.001
  scheduler_params:
    milestones:
    - 32
    gamma: 0.1
  image_normalizer:
    _target_: bliss.encoder.image_normalizer.ImageNormalizer
    bands:
    - 0
    - 1
    - 2
    - 3
    - 4
    include_original: false
    use_deconv_channel: false
    concat_psf_params: false
    num_psf_params: 6
    log_transform_stdevs:
    - -3
    - 0
    - 1
    - 3
    use_clahe: true
    clahe_min_stdev: 200
  vd_spec:
    _target_: case_studies.redshift_estimation.variational_dist.RedshiftVariationalDistSpec
    survey_bands:
    - u
    - g
    - r
    - i
    - z
    tile_slen: 4
  matcher:
    _target_: bliss.encoder.metrics.CatalogMatcher
    dist_slack: 1.0
    mag_slack: null
    mag_band: 2
  metrics:
    _target_: torchmetrics.MetricCollection
    metrics:
    - _target_: case_studies.redshift_estimation.metrics.RedshiftMeanSquaredError
    - _target_: case_studies.redshift_estimation.metrics.RedshiftCatastrophicErrorRate
    - _target_: case_studies.redshift_estimation.metrics.RedshiftNLL
  do_data_augmentation: false
  compile_model: false
  double_detect: false
  use_checkerboard: false
seed: 42
pretrained_weights: null
testing: true
