# image and sdss parameters
sdss_kwargs:
  sdss_dir: data/sdss
  run: 94
  camcol: 1
  fields:
    - 12
  stampsize: 5
  overwrite_fits_cache: False
  overwrite_cache: False
  center_subpixel: True
bands:
  - 2

# i/o parameters
sleep_checkpoint: models/sdss_sleep.ckpt
galaxy_checkpoint: models/sdss_galaxy_encoder.ckpt
binary_checkpoint: models/sdss_binary.ckpt
device: "cuda:0"
output_file: null

# coverage for tests
testing: False
