---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

encoder:
    survey_bands: ["r"]
    tile_slen: 4
    min_flux_for_loss: 1.59  # 22 magnitude (0.63 is 23 mag; 0.25 is 24 mag)
    use_double_detect: false
    image_normalizer:
        bands: [2]
        include_original: true
        concat_psf_params: true
        num_psf_params: 6  # for SDSS, 4 for DC2
        log_transform_stdevs: [0]
        use_clahe: false

cached_simulator:
    cached_data_path: /data/scratch/aakash/train_multi_field
    batch_size: 64
    splits: 0:80/80:90/90:100  # train/val/test splits as percent ranges

train:
    trainer:
        logger:
            name: PSF_MODELS
            version: multi_field_psf_param
        precision: 32
