---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: predict

paths:
    project: ${paths.root}/case_studies/psf_variation
    pretrained_models: ${paths.data}/pretrained_models

encoder:
    input_transform_params:
        use_deconv_channel: true
        concat_psf_params: true
        z-score: false
    bands: [2]
