---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

encoder:
    bands: [2]
    survey_bands: ["r"]
    tile_slen: 4
    min_flux_threshold: 1.59  # 22 magnitude (0.63 is 23 mag; 0.25 is 24 mag)
    two_layers: false
    tiles_to_crop: 1
    image_normalizer:
        include_original: true
        use_deconv_channel: true
        concat_psf_params: true
        num_psf_params: 6  # for SDSS, 4 for DC2
        log_transform_stdevs: [0]
        use_clahe: false

cached_simulator:
    cached_data_path: /data/scratch/aakash/train_multi_field
    batch_size: 64
    splits: 0:80/80:90/90:100  # train/val/test splits as percent ranges

train:
    name: PSF_MODELS
    version: multi_field_deconv_and_psf_param
    enable_early_stopping: true
    patience: 10
    pretrained_weights: null
    trainer:
        _target_: pytorch_lightning.Trainer
        logger: true
        enable_checkpointing: true
        profiler: null
        reload_dataloaders_every_n_epochs: 0
        check_val_every_n_epoch: 1
        log_every_n_steps: 10  # corresponds to n_batches
        min_epochs: 1
        max_epochs: 50
        accelerator: "gpu"
        devices: 1
    testing: true
    seed: 42
    data_source: ${cached_simulator}
    encoder: ${encoder}
    output_dir: ${paths.output}
