version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      # - python/load-cache
      - python/install-deps
      # - python/save-cache
      - run:
          name: Install Git LFS
          command: |
            apt-get update
            apt-get install -y git-lfs openssh-client
            git lfs install
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            ssh git@github.com git-lfs-authenticate "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" download
            git lfs pull
      - run:
          name: Run Tests
          command: |
            black --check .
            # pytest and pytest-cov must be in requirements.txt
            pytest --cov=./celeste/ --cov-report=xml
      - codecov/upload:
          file: ./coverage.xml

workflows:
  main:
    jobs:
      - build-and-test
