version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Run Tests
          command: |
            # pytest and coverage must be in requirements.txt
            coverage run -m pytest
            coverage report
            coverage html  # open htmlcov/index.html in a browser
      - store_artifacts:
          path: htmlcov
      - codecov/upload:
          file: .coverage
workflows:
  main:
    jobs:
      - build-and-test
