version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Run Tests
          command: |
            sudo pip install black
            black --check .
            # pytest and pytest-cov must be in requirements.txt
            pytest --cov=./src/ --cov-report=xml
      - codecov/upload:
          file: ./coverage.xml

workflows:
  main:
    jobs:
      - build-and-test
