# @package _group_
profiler: False
logger: False
checkpoint_callback: False
reload_dataloaders_every_epoch: True
check_val_every_n_epoch: 50
max_epochs: ${training.n_epochs}
min_epochs: ${training.n_epochs}
gpus: "2,"
