n_bands: ${model.decoder.n_bands}
tile_slen: ${model.decoder.tile_slen}
ptile_slen: ${model.decoder.ptile_slen}
max_detections: ${model.prior.max_sources}
channel: 17
spatial_dropout: 0.11399
dropout: 0.013123
hidden: 185
