---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

prior:
    n_tiles_h: 4
    n_tiles_w: 4
    batch_size: 2
    prob_galaxy: 0.5

simulator:
    survey: ${surveys.des}
    valid_n_batches: 1
    n_batches: 2
    num_workers: 0

encoder:
    bands: [0, 1, 2, 3]
    survey_bands: ["g", "r", "i", "z"]
    # survey_bands: ["u", "g", "r", "i", "z"]
    image_normalizer:
        z_score: false

train:
    name: "pytest_encoder"
    version: "version0"
    n_epochs: 1
    enable_early_stopping: true
    pretrained_weights: null
    seed: 42
    weight_save_path: null
    trainer:
        logger: false
        enable_checkpointing: true
        profiler: null
        check_val_every_n_epoch: 1
        log_every_n_steps: 1
        accelerator: "cpu"
        devices: 1
    testing: true
