---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: generate

prior:
    batch_size: 4

simulator:
    survey: ${surveys.des}

generate:
    n_batches: 3
    batch_size: 4
    max_images_per_file: 8
    cached_data_path: /data/scratch/zhteoh/871-decals-e2e-des/des_cached_dataset
