# @package _group_
num_workers: 0
deterministic: False
validation_plot_start: 1001
n_epochs: 1
trainer:
  profiler: False
  logger: False
  checkpoint_callback: False
  reload_dataloaders_every_epoch: False
  check_val_every_n_epoch: 1001
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  gpus: null
