# @package _group_
num_workers: 0
deterministic: False
seed: 42
validation_plot_start: 5
n_epochs: 200
trainer:
  profiler: False
  logger: False
  checkpoint_callback: False
  reload_dataloaders_every_epoch: False
  check_val_every_n_epoch: 50
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  gpus: "2,"
