# @package _group_
num_workers: 0
deterministic: False
plotting: False
n_epochs: 151
trainer:
  profiler: False
  logger: False
  checkpoint_callback: False
  reload_dataloaders_every_epoch: False
  check_val_every_n_epoch: 1001
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  gpus: "2,"
