# @package _group_
deterministic: False
plotting: True
n_epochs: 5
trainer:
  profiler: null
  logger: False
  checkpoint_callback: False
  reload_dataloaders_every_epoch: False
  check_val_every_n_epoch: 1
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  gpus: ${gpus}
