deterministic: False
plotting: True
n_epochs: 5
experiment: default
version: null
save_top_k: 1
trainer:
  logger: False
  checkpoint_callback: False
  profiler: null
  reload_dataloaders_every_epoch: False
  check_val_every_n_epoch: 1
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  gpus: ${gpus}
