---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

region_encoder:
    _target_: case_studies.adaptive_tiling.region_encoder.RegionEncoder
    survey_bands: ${encoder.survey_bands}
    tile_slen: ${encoder.tile_slen}
    # mysterious test failures if I write `image_normalizer: ${encoder.image_normalizer}` instead
    image_normalizer:
        _target_: bliss.encoder.image_normalizer.ImageNormalizer
        bands: ${encoder.image_normalizer.bands}
        include_original: false
        use_deconv_channel: false
        concat_psf_params: false
        log_transform_stdevs: [-3, 0, 1, 3]
        use_clahe: true
    overlap_slen: 0.4
    slack: ${encoder.slack}
    optimizer_params: ${encoder.optimizer_params}
    scheduler_params: ${encoder.scheduler_params}

