defaults:
    - _self_
    - training: sdss_autoencoder
    - override hydra/job_logging: stdout

hydra:
    output_subdir: null
    run:
        dir: .

mode: train

paths:
    root: ${oc.env:BLISS_HOME}
    sdss: ${paths.root}/data/sdss
    data: ${paths.root}/data
    project: ${paths.root}/case_studies/galsim_galaxies
    output: ${paths.project}/output

datasets:
    sdss_galaxies:
        _target_: bliss.datasets.galsim_galaxies.SingleGalsimGalaxies
        prior:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyPrior
            flux_sample: "pareto"
            min_flux: 622.0
            max_flux: 1e6
            alpha: 0.47
            a_sample: "gamma"
            a_concentration: 0.39330758068481686
            a_loc: 0.8371888967872619
            a_scale: 4.432725319432478
            a_bulge_disk_ratio: 2.0
        decoder:
            _target_: bliss.models.galsim_decoder.SingleGalsimGalaxyDecoder
            n_bands: 1
            slen: 53
            pixel_scale: 0.396
            psf_params_file: ${paths.data}/sdss/94/1/12/psField-000094-1-0012.fits
            psf_slen: 25
            psf_gauss_fwhm: null
            sdss_bands:
                - 2
        background:
            _target_: bliss.datasets.background.ConstantBackground
            background:
                - 865.0
        num_workers: 0
        batch_size: 256
        n_batches: 10
        fix_validation_set: True
        valid_n_batches: 200
    simulated:
        _target_: bliss.datasets.simulated.SimulatedDataset
        decoder: ${models.decoder}
        prior: ${models.prior}
        n_tiles_h: 10
        n_tiles_w: 10
        background:
            _target_: bliss.datasets.background.SimulatedSDSSBackground
            sdss_dir: ${paths.sdss}
            run: 94
            camcol: 1
            field: 12
            bands:
                - 2
        n_batches: 50
        batch_size: 32
        generate_device: "cuda:0"
        fix_validation_set: true
        valid_n_batches: 256
    galsim_blends:
        _target_: bliss.datasets.galsim_galaxies.GalsimBlends
        prior:
            _target_: bliss.models.galsim_decoder.UniformGalsimPrior
            single_galaxy_prior: ${datasets.sdss_galaxies.prior}
            max_n_sources: 8
            mean_sources: 3
            max_shift: 0.375
            galaxy_prob: 1.0
        decoder:
            _target_: bliss.models.galsim_decoder.FullCatalogDecoder
            single_galaxy_decoder: ${datasets.sdss_galaxies.decoder}
            slen: 40
            bp: 24
        background: ${datasets.sdss_galaxies.background}
        tile_slen: 4
        max_sources_per_tile: 1
        num_workers: 20
        batch_size: 512
        n_batches: 20

models:
    binary:
        _target_: bliss.models.binary.BinaryEncoder
        input_transform:
            _target_: bliss.models.detection_encoder.ConcatBackgroundTransform
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        channel: 8
        hidden: 128
        spatial_dropout: 0.0
        dropout: 0.0
    decoder:
        _target_: bliss.models.decoder.ImageDecoder
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        border_padding: 24
        psf_params_file: ${paths.data}/sdss/94/1/12/psField-000094-1-0012.fits
        galaxy_model:
            _target_: bliss.models.galaxy_net.OneCenteredGalaxyAE
            slen: ${models.galaxy_net.slen}
            latent_dim: ${models.galaxy_net.latent_dim}
            hidden: ${models.galaxy_net.hidden}
            n_bands: ${models.galaxy_net.n_bands}
            ckpt: ${paths.project}/models/sdss_autoencoder.pt
        psf_slen: 25
        sdss_bands:
            - 2
    detection_encoder:
        _target_: bliss.models.detection_encoder.DetectionEncoder
        input_transform:
            _target_: bliss.models.detection_encoder.ConcatBackgroundTransform
        n_bands: ${models.decoder.n_bands}
        tile_slen: ${models.decoder.tile_slen}
        ptile_slen: 52
        max_detections: ${models.prior.max_sources}
        channel: 8
        spatial_dropout: 0.0
        dropout: 0.0
        hidden: 128
        annotate_probs: True
        slack: 1.0
    galaxy_encoder:
        _target_: bliss.models.galaxy_encoder.GalaxyEncoder
        decoder: ${models.decoder}
        autoencoder: ${models.galaxy_net}
        hidden: ${models.galaxy_net.hidden}
    galaxy_net:
        _target_: bliss.models.galaxy_net.OneCenteredGalaxyAE
        slen: 53
        latent_dim: 8
        hidden: 256
        n_bands: 1
    prior:
        _target_: bliss.models.prior.ImagePrior
        n_bands: 1
        max_sources: 1
        mean_sources: 0.03
        min_sources: 0
        f_min: 622.0
        f_max: 1e6
        alpha: 0.43
        prob_galaxy: 0.7
        galaxy_prior:
            _target_: bliss.models.prior.GalaxyPrior
            n_latent_batches: 160
            autoencoder: ${models.galaxy_net}
            autoencoder_ckpt: ${paths.project}/models/sdss_autoencoder.pt
            latents_file: ${paths.project}/models/latents_simulated_sdss_galaxies.pt
            galaxy_dataset: ${datasets.sdss_galaxies}

generate:
    dataset:
    file:
    n_plots:

training:
    n_epochs: 121
    experiment: default
    version: null
    save_top_k: 1
    trainer:
        _target_: pytorch_lightning.Trainer
        logger: True
        enable_checkpointing: False
        profiler: null
        reload_dataloaders_every_n_epochs: 0
        max_epochs: ${training.n_epochs}
        min_epochs: ${training.n_epochs}
        accelerator: "gpu"
        devices: 1
        limit_train_batches: 1.0
        limit_val_batches: 1.0
        check_val_every_n_epoch: 10
        log_every_n_steps: 10 # correspond to n_batches
    testing:
        file: null
        batch_size: 32
        num_workers: 0
    weight_save_path: ${paths.project}/models/${training.name}.pt
    seed: 42

plots:
    figs:
        - "single_gal"
        - "blend_gal"
    location_checkpoint: ${paths.project}/models/sdss_detection_encoder.pt
    galaxy_checkpoint: ${paths.project}/models/sdss_galaxy_encoder.pt
    binary_checkpoint: ${paths.project}/models/sdss_binary.pt
    cachedir: ${paths.project}/output/galsim_figs_cache
    figdir: ${paths.project}/figures
    image_format: "png"
    overwrite: false
    psf_params_file: ${paths.data}/sdss/94/1/12/psField-000094-1-0012.fits
    sim_single_gals_file: ${paths.project}/models/simulated_sdss_individual_galaxies.pt
    sim_blend_gals_file: ${paths.project}/models/simulated_blended_galaxies.pt
    galsim_blends: ${datasets.galsim_blends}
    sdss_pixel_scale: 0.396
    device: "cuda:0"
    encoder:
        n_images_per_batch: 10
        n_rows_per_batch: 15
