---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

encoder:
    bands: [2, 3]
    survey_bands: ["u", "g", "r", "i", "z"]
    tile_slen: 2
    min_flux_threshold: 1.59  # 22 magnitude (0.63 is 23 mag; 0.25 is 24 mag)
    two_layers: true
    tiles_to_crop: 1

prior:
    _target_: bliss.simulator.prior.CatalogPrior
    survey_bands: ["u", "g", "r", "i", "z"]  # SDSS available band filters
    reference_band: 2  # SDSS r-band
    star_color_model_path: ${simulator.survey.dir_path}/color_models/star_gmm_nmgy.pkl
    gal_color_model_path: ${simulator.survey.dir_path}/color_models/gal_gmm_nmgy.pkl
    n_tiles_h: 32
    n_tiles_w: 32
    tile_slen: 2
    batch_size: 64
    max_sources: 5
    mean_sources: 0.48
    min_sources: 0
    prob_galaxy: 0.0
    star_flux_min: 0.63  # i.e., 23 magnitude
    star_flux_max: 1014
    star_flux_alpha: 0.5

generate:
    n_batches: 512
    cached_data_path: /data/scratch/regier/m2

cached_simulator:
    cached_data_path: /data/scratch/regier/m2
    batch_size: 32

predict:
    dataset:
        _target_: bliss.surveys.sdss.SloanDigitalSkySurvey
        dir_path: ${paths.sdss}
        fields:
            - run: 2583
              camcol: 2
              fields: [136]
        psf_config:
            pixel_scale: 0.396
            psf_slen: 25
        pixel_shift: 2
        align_to_band: null
        load_image_data: true
        crop_config: [624, 736, 304, 416]
    trainer: ${train.trainer}
    encoder: ${encoder}
    weight_save_path: ${paths.root}/case_studies/dependent_tiling/m2.pt
    device: "cuda:0"
    is_simulated: false
