---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

encoder:
    bands: [2]

prior:
    _target_: bliss.simulator.prior.CatalogPrior
    survey_bands: ["u", "g", "r", "i", "z"]  # SDSS available band filters
    reference_band: 2  # SDSS r-band
    star_color_model_path: ${simulator.survey.dir_path}/color_models/star_gmm_nmgy.pkl
    gal_color_model_path: ${simulator.survey.dir_path}/color_models/gal_gmm_nmgy.pkl
    n_tiles_h: 20
    n_tiles_w: 20
    tile_slen: 4
    batch_size: 64
    max_sources: 4
    mean_sources: 0.2
    min_sources: 0
    prob_galaxy: 0.0
    star_flux_min: 0.63094948
    star_flux_max: 1014
    star_flux_alpha: 0.43
    galaxy_flux_min: 0.6301037
    galaxy_flux_max: 1013
    galaxy_alpha: 0.47
    galaxy_a_concentration: 0.39330758068481686
    galaxy_a_loc: 0.8371888967872619
    galaxy_a_scale: 4.432725319432478
    galaxy_a_bd_ratio: 2.0

surveys:
    sdss:
        _target_: bliss.surveys.sdss.SloanDigitalSkySurvey
        dir_path: ${paths.sdss}
        fields:
            - run: 2583
              camcol: 2
              fields: [136]
        psf_config:
            pixel_scale: 0.396
            psf_slen: 25
        pixel_shift: 2
