---
defaults:
    - ../../conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    project: ${paths.root}/case_studies/summer_template
    output: ${paths.project}/output
    pretrained_models: ${paths.data}/pretrained_models

simulator:
    prior:
        max_sources: 1
        mean_sources: 0.2
        min_sources: 0
    background:
        _target_: bliss.simulator.background.SimulatedSDSSBackground
        sdss_dir: ${paths.sdss}
        run: 94
        camcol: 1
        field: 12
        bands: [2]

training:
    name: "encoder"
    version: "sdss"
    pretrained_weights: ${paths.pretrained_models}/crowded_field.pt
    weight_save_path: ${paths.output}/${training.name}/${training.version}.pt
    seed: 42
