---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

my_variational_factors:
  - _target_: case_studies.dc2_cataloging.utils.variational_dist.MyBernoulliFactor
    name: n_sources
    sample_rearrange: null
    nll_rearrange: null
    nll_gating: null
  - _target_: bliss.encoder.variational_dist.TDBNFactor
    name: locs
    sample_rearrange: b ht wt d -> b ht wt 1 d
    nll_rearrange: b ht wt 1 d -> b ht wt d
    nll_gating:
      _target_: bliss.encoder.variational_dist.SourcesGating
  - _target_: case_studies.dc2_cataloging.utils.variational_dist.MyBernoulliFactor
    name: source_type
    sample_rearrange: b ht wt -> b ht wt 1 1
    nll_rearrange: b ht wt 1 1 -> b ht wt
    nll_gating:
      _target_: bliss.encoder.variational_dist.SourcesGating
  - _target_: bliss.encoder.variational_dist.LogNormalFactor
    name: star_fluxes
    dim: 6
    sample_rearrange: b ht wt d -> b ht wt 1 d
    nll_rearrange: b ht wt 1 d -> b ht wt d
    nll_gating:
      _target_: bliss.encoder.variational_dist.StarGating
  - _target_: bliss.encoder.variational_dist.LogNormalFactor
    name: galaxy_fluxes
    dim: 6
    sample_rearrange: b ht wt d -> b ht wt 1 d
    nll_rearrange: b ht wt 1 d -> b ht wt d
    nll_gating:
      _target_: bliss.encoder.variational_dist.GalaxyGating
  # - _target_: bliss.encoder.variational_dist.BivariateNormalFactor
  #   name: shear
  #   sample_rearrange: b ht wt d -> b ht wt 1 d
  #   nll_rearrange: b ht wt 1 d -> b ht wt d
  #   nll_gating:
  #     _target_: case_studies.dc2_cataloging.utils.variational_dist.Cosmodc2Gating
  - _target_: bliss.encoder.variational_dist.BivariateNormalFactor
    name: ellipticity
    sample_rearrange: b ht wt d -> b ht wt 1 d
    nll_rearrange: b ht wt 1 d -> b ht wt d
    nll_gating:
      _target_: case_studies.dc2_cataloging.utils.variational_dist.Cosmodc2Gating

my_metrics:
  detection_performance:
    _target_: bliss.encoder.metrics.DetectionPerformance
    bin_cutoffs: [23.9, 24.1, 24.5, 24.9, 25.6]
    bin_type: njymag
  detection_performance_star:
    _target_: bliss.encoder.metrics.DetectionPerformance
    bin_cutoffs: [23.9, 24.1, 24.5, 24.9, 25.6]
    bin_type: njymag
    filter_list:
      - _target_: bliss.encoder.metrics.SourceTypeFilter
        filter_type: star
  detection_performance_galaxy:
    _target_: bliss.encoder.metrics.DetectionPerformance
    bin_cutoffs: [23.9, 24.1, 24.5, 24.9, 25.6]
    bin_type: njymag
    filter_list:
      - _target_: bliss.encoder.metrics.SourceTypeFilter
        filter_type: galaxy
  detection_performance_one_source_mask:
    _target_: bliss.encoder.metrics.DetectionPerformance
    bin_cutoffs: [23.9, 24.1, 24.5, 24.9, 25.6]
    bin_type: njymag
    filter_list:
      - _target_: case_studies.dc2_cataloging.utils.metrics.SourceCountFilter
        filter_source_count: 1m
  detection_performance_two_sources_mask:
    _target_: bliss.encoder.metrics.DetectionPerformance
    bin_cutoffs: [23.9, 24.1, 24.5, 24.9, 25.6]
    bin_type: njymag
    filter_list:
      - _target_: case_studies.dc2_cataloging.utils.metrics.SourceCountFilter
        filter_source_count: 2m
  detection_performance_more_than_two_sources_mask:
    _target_: bliss.encoder.metrics.DetectionPerformance
    bin_cutoffs: [23.9, 24.1, 24.5, 24.9, 25.6]
    bin_type: njymag
    filter_list:
      - _target_: case_studies.dc2_cataloging.utils.metrics.SourceCountFilter
        filter_source_count: 2plus
  source_type_accuracy:
    _target_: bliss.encoder.metrics.SourceTypeAccuracy
    bin_cutoffs: [23.9, 24.1, 24.5, 24.9, 25.6]
    bin_type: njymag
  flux_error:
    _target_: bliss.encoder.metrics.FluxError
    survey_bands: ${encoder.survey_bands}
  # shear_error:
  #   _target_: case_studies.dc2_cataloging.utils.metrics.ShearMSE
  #   bin_cutoffs: [23.9, 24.1, 24.5, 24.9, 25.6]
  #   bin_type: njymag
  ellipticity_error:
    _target_: case_studies.dc2_cataloging.utils.metrics.EllipticityMSE
    bin_cutoffs: [23.9, 24.1, 24.5, 24.9, 25.6]
    bin_type: njymag

my_image_normalizers:
  null_noramlize:
      _target_: case_studies.dc2_cataloging.utils.image_normalizer.NullNormalizer

encoder:
    _target_: case_studies.dc2_multidetection.utils.encoder.MultiDetectEncoder
    survey_bands: [u, g, r, i, z, y]
    reference_band: 2
    tile_slen: ${surveys.dc2.tile_slen}
    optimizer_params:
        lr: 1e-3
    scheduler_params:
        milestones: [32]
        gamma: 0.1
    image_normalizers: ${my_image_normalizers}
    var_dist:
        _target_: case_studies.dc2_multidetection.utils.variational_dist.MultiVariationalDist
        tile_slen: ${surveys.dc2.tile_slen}
        factors: ${my_variational_factors}
        repeat_times: 8
        assigner:
          _target_: case_studies.dc2_multidetection.utils.variational_dist.TaskAlignedAssigner
    one_to_topk: 3
    matcher:
        _target_: bliss.encoder.metrics.CatalogMatcher
        dist_slack: 1.0
        mag_slack: null
        mag_band: 2  # SDSS r-band
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        compute_groups: false
        metrics: ${my_metrics}
    sample_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        compute_groups: false
        metrics: ${my_metrics}
    sample_image_renders:
        _target_: torchmetrics.MetricCollection
        metrics:
          - _target_: bliss.encoder.sample_image_renders.PlotSampleImages
            frequency: 1
            restrict_batch: 0
            tiles_to_crop: 0
            tile_slen: ${surveys.dc2.tile_slen}
    use_double_detect: false
    use_checkerboard: false

train:
    trainer:
        logger:
            name: DC2_multidetection_exp
            version: exp_08-05-4  # change it before running the code
        devices: [3]  # change it before running the code
        use_distributed_sampler: false  # disable this because we use the self-defined distributed sampler
        precision: 32-true
    data_source: ${surveys.dc2}
    pretrained_weights: null
    seed: 8282
