---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

encoder:
    survey_bands: ["g", "i", "r", "u", "y", "z"]
    tile_slen: 4
    double_detect: false
    tiles_to_crop: 1
    image_normalizer:
        bands: [0, 1, 2, 3, 4, 5]
        num_psf_params: 4  # for SDSS, 4 for DC2
        log_transform_stdevs: []
        use_clahe: false


surveys:
    dc2:
        data_dir: /data/scratch/dc2local/run2.2i-dr6-v4/coadd-t3828-t3829/deepCoadd-results/
        cat_path: ${paths.dc2}/merged_catalog/merged_catalog_psf_100000.pkl
        batch_size: 64
        n_split: 50
        image_lim: [4000, 4000]
        for_plotting: false

train:
    trainer:
        logger:
            name: DC2
            version: DC2_origin
        precision: 32
        # strategy:
        #   _target_: pytorch_lightning.strategies.DDPStrategy
        #   process_group_backend: nccl
        #   timeout:
        #     _target_: datetime.timedelta
        #     seconds: 180000
        # devices: -1
    data_source: ${surveys.dc2}
    pretrained_weights: null
