---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

encoder:
    survey_bands: ["g", "i", "r", "u", "y", "z"]
    tile_slen: 4
    double_detect: false
    tiles_to_crop: 1
    do_data_augmentation: true
    image_normalizer:
        bands: [0, 1, 2, 3, 4, 5]
        num_psf_params: 4  # for SDSS, 4 for DC2
        log_transform_stdevs: []
        use_clahe: false
        asinh_params:
            scale: 0.1
            thresholds: [-3, 0, 1, 3]
        concat_psf_params: true


surveys:
    dc2:
        _target_: bliss.surveys.dc2_new.DC2
        data_dir: /data/scratch/dc2local/run2.2i-dr6-v4/coadd-t3828-t3829/deepCoadd-results/
        split_result_folder: split_results_05_15_2024
        cat_path: ${paths.dc2}/merged_catalog/merged_catalog_with_flux_over_100.pkl
        batch_size: 64
        n_split: 50
        image_lim: [4000, 4000]
        num_workers: 4
        for_plotting: false

train:
    trainer:
        logger:
            name: DC2_psf_aug_asinh
            version: DC2_psf_aug_asinh
        precision: 32
        strategy:
          _target_: pytorch_lightning.strategies.DDPStrategy
          process_group_backend: nccl
          timeout:
            _target_: datetime.timedelta
            seconds: 180000
        devices: [0, 1]
    data_source: ${surveys.dc2}
    pretrained_weights: null
