---
defaults:
    - full_train_config
    - _self_
    - override hydra/job_logging: stdout

encoder:
    tiles_to_crop: 0
    image_normalizer:
        asinh_params:
            scale: 0.1
            thresholds: [-25, -3, 0.5, 9, 44]
