---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    cached_data: /data/scratch/regier/toy_example_10_percent

# this prior is sdss-like, except for the flux distribution, which is easier
# (i.e, flatter, always greater than 3 nmgy, and always less than 100 nmgy).
# the source density is higher too.
# greatly increasing the source density too here
prior:
    # not exactly the mean because the max sources per tile is
    # clipped at 1, but close
    mean_sources: 0.1  # expect 36 sources per 80x80 image
    # truncpareto support is [scale + loc, truncation * scale + loc]
    star_flux_exponent: 0.1
    star_flux_truncation: 100
    star_flux_loc: 0
    star_flux_scale: 1.3
    galaxy_flux_exponent: 0.01
    galaxy_flux_truncation: 100
    galaxy_flux_loc: 0
    galaxy_flux_scale: 1.3

variational_factors:
    - _target_: bliss.encoder.variational_dist.BernoulliFactor
      name: n_sources
      sample_rearrange: null
      nll_rearrange: null
      nll_gating: null
    - _target_: bliss.encoder.variational_dist.TDBNFactor
      name: locs
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 d -> b ht wt d"
      nll_gating:
          _target_: bliss.encoder.variational_dist.SourcesGating
    - _target_: bliss.encoder.variational_dist.BernoulliFactor
      name: source_type
      sample_rearrange: "b ht wt -> b ht wt 1 1"
      nll_rearrange: "b ht wt 1 1 -> b ht wt"
      nll_gating:
          _target_: bliss.encoder.variational_dist.SourcesGating
    - _target_: bliss.encoder.variational_dist.LogNormalFactor
      name: star_fluxes
      dim: 1
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 d -> b ht wt d"
      nll_gating:
          _target_: bliss.encoder.variational_dist.StarGating
    - _target_: bliss.encoder.variational_dist.LogNormalFactor
      name: galaxy_fluxes
      dim: 1
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 d -> b ht wt d"
      nll_gating:
          _target_: bliss.encoder.variational_dist.GalaxyGating
    - _target_: bliss.encoder.variational_dist.LogitNormalFactor
      name: galaxy_disk_frac
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating:
          _target_: bliss.encoder.variational_dist.GalaxyGating
    - _target_: bliss.encoder.variational_dist.LogitNormalFactor
      name: galaxy_beta_radians
      high: 3.1415926
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating:
          _target_: bliss.encoder.variational_dist.GalaxyGating
    - _target_: bliss.encoder.variational_dist.LogitNormalFactor
      name: galaxy_disk_q
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating:
          _target_: bliss.encoder.variational_dist.GalaxyGating
    - _target_: bliss.encoder.variational_dist.LogNormalFactor
      name: galaxy_a_d
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating:
          _target_: bliss.encoder.variational_dist.GalaxyGating
    - _target_: bliss.encoder.variational_dist.LogitNormalFactor
      name: galaxy_bulge_q
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating:
          _target_: bliss.encoder.variational_dist.GalaxyGating
    - _target_: bliss.encoder.variational_dist.LogNormalFactor
      name: galaxy_a_b
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating:
          _target_: bliss.encoder.variational_dist.GalaxyGating

my_metrics:
    detection_performance:
        _target_: bliss.encoder.metrics.DetectionPerformance
        bin_cutoffs: [19, 19.4, 19.8, 20.2, 20.6, 21, 21.4, 21.8]
        bin_type: "mag"
        ref_band: 0

encoder:
    survey_bands: ['r']
    reference_band: 0
    use_checkerboard: true
    matcher:
        _target_: bliss.encoder.metrics.CatalogMatcher
        dist_slack: 1.0
        mag_slack: null
        mag_band: 2  # SDSS r-band
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: "partial"
        metrics: ${my_metrics}
    sample_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: "partial"
        metrics: ${my_metrics}

cached_simulator:
    train_transforms:
        - _target_: bliss.cached_dataset.OneBandTransform
          band_idx: 2
        - _target_: bliss.data_augmentation.RotateFlipTransform
    nontrain_transforms:
        - _target_: bliss.cached_dataset.OneBandTransform
          band_idx: 2
