---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    cached_data: /data/scratch/regier/toy_example

# this prior is sdss-like, except for the flux distribution, which is easier
# (i.e, flatter, always greater than 3 nmgy, and always less than 100 nmgy).
# the source density is higher too.
prior:
    star_flux_exponent: 0.01
    star_flux_truncation: 100
    star_flux_loc: 3.0
    star_flux_scale: 3.0
    galaxy_flux_exponent: 0.01
    galaxy_flux_truncation: 100
    galaxy_flux_scale: 3.0
    galaxy_flux_loc: 3.0

variational_factors:
    - _target_: bliss.encoder.variational_dist.BernoulliFactor
      name: n_sources
      sample_rearrange: null
      nll_rearrange: null
      nll_gating: null
    - _target_: bliss.encoder.variational_dist.TDBNFactor
      name: locs
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 d -> b ht wt d"
      nll_gating: n_sources
    - _target_: bliss.encoder.variational_dist.BernoulliFactor
      name: source_type
      sample_rearrange: "b ht wt -> b ht wt 1 1"
      nll_rearrange: "b ht wt 1 1 -> b ht wt"
      nll_gating: n_sources
    - _target_: bliss.encoder.variational_dist.LogNormalFactor
      name: star_fluxes
      dim: 1
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 d -> b ht wt d"
      nll_gating: is_star
    - _target_: bliss.encoder.variational_dist.LogNormalFactor
      name: galaxy_fluxes
      dim: 1
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 d -> b ht wt d"
      nll_gating: is_galaxy
    - _target_: bliss.encoder.variational_dist.LogitNormalFactor
      name: galaxy_disk_frac
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating: is_galaxy
    - _target_: bliss.encoder.variational_dist.LogitNormalFactor
      name: galaxy_beta_radians
      high: 3.1415926
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating: is_galaxy
    - _target_: bliss.encoder.variational_dist.LogitNormalFactor
      name: galaxy_disk_q
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating: is_galaxy
    - _target_: bliss.encoder.variational_dist.LogNormalFactor
      name: galaxy_a_d
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating: is_galaxy
    - _target_: bliss.encoder.variational_dist.LogitNormalFactor
      name: galaxy_bulge_q
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating: is_galaxy
    - _target_: bliss.encoder.variational_dist.LogNormalFactor
      name: galaxy_a_b
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 1 -> b ht wt 1"
      nll_gating: is_galaxy

my_metrics:
    detection_performance:
        _target_: bliss.encoder.metrics.DetectionPerformance
        mag_bin_cutoffs: [19, 19.4, 19.8, 20.2, 20.6, 21, 21.4, 21.8]
        mag_band: 0

encoder:
    survey_bands: ['r']
    reference_band: 0
    matcher:
        _target_: bliss.encoder.metrics.CatalogMatcher
        dist_slack: 1.0
        mag_slack: null
        mag_band: 2  # SDSS r-band
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: "partial"
        metrics: ${my_metrics}

cached_simulator:
    train_transforms:
        - _target_: bliss.cached_dataset.OneBandTransform
          band_idx: 2
        - _target_: bliss.data_augmentation.RotateFlipTransform
    nontrain_transforms:
        - _target_: bliss.cached_dataset.OneBandTransform
          band_idx: 2
