---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    cached_data: /data/scratch/regier/20percent

my_metrics:
    detection_performance:
        _target_: bliss.encoder.metrics.DetectionPerformance
        mag_bin_cutoffs: [19, 19.4, 19.8, 20.2, 20.6, 21, 21.4, 21.8]
        mag_band: 0

encoder:
    survey_bands: ['r']
    reference_band: 0
    matcher:
        _target_: bliss.encoder.metrics.CatalogMatcher
        dist_slack: 1.0
        mag_slack: null
        mag_band: 2  # SDSS r-band
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: "partial"
        metrics: ${my_metrics}

cached_simulator:
    train_transforms:
        - _target_: bliss.cached_dataset.OneBandTransform
          band_idx: 2
        - _target_: bliss.data_augmentation.RotateFlipTransform
    nontrain_transforms:
        - _target_: bliss.cached_dataset.OneBandTransform
          band_idx: 2
