# @package _global_
training:
  name: "sdss_detection_encoder"
  model: ${models.detection_encoder}
  dataset: ${datasets.simulated}
  # n_epochs: 1501
  n_epochs: 300
  save_top_k: 10
  trainer:
    enable_checkpointing: true
    check_val_every_n_epoch: 5
