---
defaults:
    - full_train_config.yaml
    - _self_
    - override hydra/job_logging: stdout

train:
    trainer:
        logger:
            name: DC2_debug
            version: DC2_debug
        devices: [7]

surveys:
    dc2:
        split_results_dir: ${paths.output}/dc2_split_results
        split_processes_num: 4
        subset_fraction: 0.1
