---
defaults:
    - train_config
    - _self_
    - override hydra/job_logging: stdout

# encoder:
#     tiles_to_crop: 0

surveys:
    dc2:
        prepare_data_processes_num: 1
        num_workers: 0
