---
defaults:
    - train_config
    - _self_
    - override hydra/job_logging: stdout

train:
    trainer:
        logger:
            name: DC2_debug
            version: DC2_debug
        devices: [0]

surveys:
    dc2:
        split_processes_num: 4
        subset_fraction: 0.1
