---
defaults:
    - ../../conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    project: ${paths.root}/case_studies/721_diskrw_gsimages
    output: ${paths.project}/output
    pretrained_models: ${paths.data}/pretrained_models

simulator:
    n_batches: 5
    background:
        _target_: bliss.simulator.background.SimulatedSDSSBackground
        sdss_dir: ${paths.sdss}
        run: 94
        camcol: 1
        field: 12
        bands: [2]

cached_simulator:
    file_data_capacity: 150

training:
    name: "encoder"
    version: "sdss"
    pretrained_weights: ${paths.pretrained_models}/sdss.pt
    weight_save_path: ${paths.output}/${training.name}/${training.version}.pt
    seed: 42
    use_cached_simulator: true
