---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    project: ${paths.root}/case_studies/diskrw_gsimages_721
    output: ${paths.project}/output
    pretrained_models: ${paths.data}/pretrained_models

simulator:
    prior:
        mean_sources: 0.2
        n_tiles_h: 16
        n_tiles_w: 16
    background:
        _target_: bliss.simulator.background.SimulatedSDSSBackground
        sdss_dir: ${paths.sdss}
        run: 94
        camcol: 1
        field: 12
        bands: [2]

cached_simulator:
    # ~50GB, 16x16 sq. tiles, 0.2 mean sources
    #  training set  : 112 files * 144 batches * 64 images/batch = 1,032,192 images (80%)
    #  validation set: 14 files * 144 batches * 64 images/batch = 129,024 images (10%)
    #  testing set   : 14 files * 144 batches * 64 images/batch = 129,024 images (10%)
    n_train_batches: 10752
    val_split_file_idxs: [113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126]
    test_split_file_idxs: null # [127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140]

generate:
    # 16x16: 576, 9216 (144 batches / file)
    # 20x20: 384, 6144 (96 batches / file)
    # 48x48: 64, 1024 (16 batches / file)
    # 100x100: 16, 256 (4 batches / file)
    n_batches: 1
    batch_size: 64
    max_images_per_file: 64
    cached_data_path: /data/scratch/zhteoh/cached_dataset_${simulator.prior.mean_sources}_${simulator.prior.n_tiles_h}tiles_50GB

train:
    name: "encoder"
    version: "sdss"
    pretrained_weights: ${paths.pretrained_models}/sdss.pt
    weight_save_path: ${paths.output}/${training.name}/${training.version}.pt
    seed: 42
    use_cached_simulator: true
