---
defaults:
    - ../../conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    project: ${paths.root}/case_studies/diskrw_gsimages_721
    output: ${paths.project}/output
    pretrained_models: ${paths.data}/pretrained_models

simulator:
    background:
        _target_: bliss.simulator.background.SimulatedSDSSBackground
        sdss_dir: ${paths.sdss}
        run: 94
        camcol: 1
        field: 12
        bands: [2]

cached_simulator:
    n_train_batches: 192
    val_split_file_idxs: [96, 97, 98]
    test_split_file_idxs: [99, 100, 101]

generate:
    n_batches: 6
    max_images_per_file: 150

training:
    name: "encoder"
    version: "sdss"
    pretrained_weights: ${paths.pretrained_models}/sdss.pt
    weight_save_path: ${paths.output}/${training.name}/${training.version}.pt
    seed: 42
    use_cached_simulator: true
