---
defaults:
    - ../../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    cached_data: /data/scratch/regier/m2_jul31

variational_factors:
    - _target_: bliss.encoder.variational_dist.BernoulliFactor
      name: n_sources
      sample_rearrange: null
      nll_rearrange: null
      nll_gating: null
    - _target_: bliss.encoder.variational_dist.BernoulliFactor
      name: source_type
      sample_rearrange: "b ht wt -> b ht wt 1 1"
      nll_rearrange: "b ht wt 1 1 -> b ht wt"
      nll_gating:
          _target_: bliss.encoder.variational_dist.SourcesGating
    - _target_: bliss.encoder.variational_dist.LogNormalFactor
      name: star_fluxes
      dim: 1
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 d -> b ht wt d"
      nll_gating:
          _target_: bliss.encoder.variational_dist.StarGating
    - _target_: bliss.encoder.variational_dist.DiscretizedUnitBoxFactor
      name: locs
      sample_rearrange: "b ht wt d -> b ht wt 1 d"
      nll_rearrange: "b ht wt 1 d -> b ht wt d"
      nll_gating:
          _target_: bliss.encoder.variational_dist.SourcesGating

star_metrics:
    detection_performance:
        _target_: bliss.encoder.metrics.DetectionPerformance
        bin_cutoffs: [19, 19.4, 19.8, 20.2, 20.6, 21, 21.4, 21.8, 22.065]
        bin_type: mag
        exclude_last_bin: true
        ref_band: 0

nopsf_image_normalizers:
    clahe:
        _target_: bliss.encoder.image_normalizer.ClaheNormalizer
        min_stdev: 200
    asinh:
        _target_: bliss.encoder.image_normalizer.AsinhQuantileNormalizer
        q: [0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99, 0.999, 0.9999, 0.99999]

encoder:
    tile_slen: 2
    survey_bands: ['r']
    reference_band: 0
    use_checkerboard: true
    use_double_detect: true
    image_normalizers: ${nopsf_image_normalizers}
    matcher:
        _target_: bliss.encoder.metrics.CatalogMatcher
        dist_slack: 0.5
        mag_slack: 0.5
        mag_band: 0  # SDSS r-band
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        metrics: ${star_metrics}
    sample_metrics:
        _convert_: "partial"
        _target_: torchmetrics.MetricCollection
        metrics:
            two_point:
                _target_: case_studies.spatial_tiling.m2.metrics.TwoPointMetric
    sample_image_renders: null
    optimizer_params:
        lr: 1e-3
    scheduler_params:
        milestones: []
        gamma: 0.1

prior:
    _target_: bliss.simulator.prior.CatalogPrior
    survey_bands: ["u", "g", "r", "i", "z"]  # SDSS available band filters
    reference_band: 2  # SDSS r-band
    star_color_model_path: ${paths.sdss}/color_models/star_gmm_nmgy.pkl
    gal_color_model_path: ${paths.sdss}/color_models/gal_gmm_nmgy.pkl
    n_tiles_h: 56
    n_tiles_w: 56
    batch_size: 32
    max_sources: 6
    mean_sources: 0.8029160898574715
    min_sources: 0
    prob_galaxy: 0.0
    star_flux_exponent: 0.9859821185389767
    star_flux_truncation: 5685.588160703261
    star_flux_loc: -1.162430157551662
    star_flux_scale: 1.4137911256506595

decoder:
    tile_slen: 2
    with_dither: false

surveys:
    sdss:
        # need to override this for proper data generation.
        # these settings are also used for prediction.
        fields:
            - run: 2583
              camcol: 2
              fields: [136]
        align_to_band: null
        background_offset: 80

generate:
    n_image_files: 64
    n_batches_per_file: 64
    cached_data_path: ${paths.cached_data}
    store_full_catalog: true

cached_simulator:
    cached_data_path: ${paths.cached_data}
    batch_size: 4
    num_workers: 8
    train_transforms:
        - _target_: bliss.cached_dataset.OneBandTransform
          band_idx: 2
        - _target_: bliss.cached_dataset.FullCatalogToTileTransform
          tile_slen: 2
          max_sources: 6
        - _target_: bliss.cached_dataset.FluxFilterTransform
          reference_band: 0  # formerly 2 before the OneBandTransform
          min_flux: 0.9419
        - _target_: bliss.data_augmentation.RotateFlipTransform
    nontrain_transforms:
        - _target_: bliss.cached_dataset.OneBandTransform
          band_idx: 2
        - _target_: bliss.cached_dataset.FullCatalogToTileTransform
          tile_slen: 2
          max_sources: 6
        - _target_: bliss.cached_dataset.FluxFilterTransform
          reference_band: 0
          min_flux: 0.9419  # (1.59 is 22 mag; 0.63 is 23 mag; 0.25 is 24 mag)

train:
    trainer:
        precision: 32-true
    seed: null

predict:
    dataset:
        load_image_data: true
        crop_to_bands: [2]
        crop_to_hw: [624, 736, 304, 416]
    weight_save_path: null
