# @package _group_
name: "CatsimGalaxies"
catalog_file: ${paths.root}/data/OneDegSq.fits
n_batches: 20
batch_size: 128
num_workers: 8
renderer:
  survey_name: "SDSS"
  slen: 41
  n_bands: 1
  deviate_center: False
  noise_factor: 0.1
  psf_file: ${paths.root}/data/sdss-002583-2-0136-psf-r.fits
