# @package _group_
name: "CatsimGalaxies"
catalog_file: ${paths.root}/data/OneDegSq.fits
n_batches: 20
batch_size: 64
num_workers: 16
renderer:
  survey_name: "SDSS"
  slen: 51
  snr: 200
  n_bands: 1
  deviate_center: False
  add_noise: True
  psf_file: ${paths.root}/data/sdss-002583-2-0136-psf-r.fits
