# @package _group_
name: "CatsimGalaxies"
catalog_file: ${paths.root}/data/OneDegSq.fits
n_batches: 10
num_workers: 4
batch_size: 320
renderer:
  survey_name: "LSST"
  slen: 51
  snr: 200
  bands:
    - "i"
  deviate_center: False
  preserve_flux: False
  add_noise: True
