# @package _group_
name: "CatsimGalaxies"
catalog_file: ${paths.root}/data/OneDegSq.fits
n_batches: 100
batch_size: 500
num_workers: 10
renderer:
  survey_name: "LSST"
  slen: 51
  snr: 200
  n_bands: 1
  deviate_center: False
  preserve_flux: False
  add_noise: True
