---
defaults:
    - _self_
    - override hydra/job_logging: stdout

# completely disable hydra logging
# https://github.com/facebookresearch/hydra/issues/910
hydra:
    output_subdir: null
    run:
        dir: .

paths:
    cached_data: /data/scratch/descwl/weak_lensing_img2048_WLD_80_star_max_100_draw_bright_with_filter_varying_shear
    output: /home/twhit/bliss

cached_simulator:
    _target_: bliss.cached_dataset.CachedSimulatedDataModule
    batch_size: 1
    splits: 0:70/70:80/80:100
    num_workers: 1
    cached_data_path: ${paths.cached_data}
    train_transforms: []
    nontrain_transforms: []

variational_factors:
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: shear_1
    nll_gating: null
  - _target_: bliss.encoder.variational_dist.NormalFactor
    name: shear_2
    nll_gating: null

lensing_normalizers_nan:
    nan:
        _target_: case_studies.weak_lensing.image_normalizer.NanNormalizer

lensing_metrics:
    _target_: case_studies.weak_lensing.metrics.WeakLensingMetrics
    num_redshift_bins: 1

lensing_plots:
    _target_: case_studies.weak_lensing.plots.WeakLensingPlots
    frequency: 1
    save_local: ${paths.output}/${train.trainer.logger.name}/${train.trainer.logger.version}/lensing_plots

encoder:
    _target_: case_studies.weak_lensing.encoder.WeakLensingEncoder
    n_bands: 3
    res_init: 2048  # num pixels per side
    res_midpoint: 128
    res_final: 1  # num tiles per side
    ch_init: 64
    ch_max: 512
    ch_final: 128
    initial_downsample: true
    more_up_layers: false
    num_bottleneck_layers: 0
    image_normalizers: ${lensing_normalizers_nan}
    var_dist:
        _target_: bliss.encoder.variational_dist.VariationalDist
        tile_slen: 2048
        factors: ${variational_factors}
    optimizer_params:
        lr: 1e-4
    scheduler_params:
        milestones: []
        gamma: 1.0
    loss_plots_location: ${paths.output}/${train.trainer.logger.name}/${train.trainer.logger.version}/loss_plots
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${lensing_metrics}
    sample_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${lensing_metrics}
    sample_image_renders:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        metrics: ${lensing_plots}

mode: train

train:
    trainer:
        _target_: pytorch_lightning.Trainer
        logger:
            _target_: pytorch_lightning.loggers.TensorBoardLogger
            save_dir: ${paths.output}
            name: WeakLensingResultsDescwl
            version: ${now:%Y-%m-%d_%H-%M}
            default_hp_metric: false
        reload_dataloaders_every_n_epochs: 0
        check_val_every_n_epoch: 1
        log_every_n_steps: 10
        max_epochs: 300
        accelerator: gpu
        devices: 1
        precision: 32-true
    callbacks:
        checkpointing:
            _target_: pytorch_lightning.callbacks.ModelCheckpoint
            filename: "encoder_{epoch}"
            save_top_k: 1
            verbose: true
            monitor: val/_loss
            mode: min
            save_on_train_epoch_end: false
        early_stopping:
            _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
            monitor: val/_loss
            mode: min
            patience: 100
    data_source: ${cached_simulator}
    encoder: ${encoder}
    seed: 123123
    pretrained_weights: null
    ckpt_path: null
    matmul_precision: high
