image_path: /data/scratch/taodingr/weak_lensing/descwl/WLD_density_240/images_WLD_density_240.pt
catalog_path: /data/scratch/taodingr/weak_lensing/descwl/WLD_density_240/catalog_WLD_density_240.pt
setting: WLD_density_240
shear_setting: varying
n_tiles_per_side: 1
