"""
AnaCal processing script for weak lensing simulations.
Processes images generated by generate_images.py and computes shear measurements.

Usage:
    python run_anacal.py config_anacal.yaml
    python run_anacal.py  # uses config_anacal.yaml in same directory
"""

import glob
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime

import anacal
import galsim
import numpy as np
import torch
import yaml
from tqdm import tqdm

# =============================================================================
# Default Configuration
# =============================================================================

DEFAULT_CONFIG = {
    "npix": 64,  # PSF cutout size
    "sigma_arcsec": 0.52,  # Gaussian smoothing sigma
    "mag_zero": 30.0,  # Zero point magnitude
    "pixel_scale": 0.2,  # Arcsec per pixel
    "combine_method": "inverse_variance",  # or 'mean'
    "mask_combine_method": "union",  # or 'first_only', 'intersection'
}


# =============================================================================
# AnaCal Utility Classes
# =============================================================================


class GalSimPsfWrapper(anacal.psf.BasePsf):
    """Wrapper to make GalSim PSF objects compatible with anacal."""

    def __init__(self, galsim_psf, pixel_scale, npix=64, is_variable=False):
        self.galsim_psf = galsim_psf
        self.pixel_scale = pixel_scale
        self.npix = npix
        self.is_variable = is_variable
        self.shape = None  # Signals to anacal that it's not an array

    def draw(self, x, y):
        """Draw PSF at position (x, y)."""
        if self.is_variable:
            pos = galsim.PositionD(x, y)
            psf_at_pos = self.galsim_psf.getPSF(pos)
        else:
            psf_at_pos = self.galsim_psf

        return psf_at_pos.drawImage(
            nx=self.npix, ny=self.npix, scale=self.pixel_scale, method="auto"
        ).array.astype(np.float64)


# =============================================================================
# Band Combination Functions
# =============================================================================


def combine_multiband_images(images_tensor, band_variances=None, method="inverse_variance"):
    """
    Combine multi-band images into single image for anacal processing.

    Parameters
    ----------
    images_tensor : torch.Tensor
        Shape: [n_bands, height, width]
    band_variances : dict or None
        Dictionary mapping band names to variance values
    method : str
        'inverse_variance': Weight by 1/variance (xlens approach)
        'mean': Simple average across bands

    Returns
    -------
    combined_image : torch.Tensor
        Single image [height, width]
    combined_variance : float
        Combined variance value
    """
    if method == "inverse_variance":
        if band_variances is not None:
            weights = []
            band_names = ["g", "r", "i", "z"][: images_tensor.shape[0]]

            for band in band_names:
                variance_value = band_variances.get(band, 0.354)
                weights.append(1.0 / variance_value)

            weights = torch.tensor(weights, dtype=torch.float32)
        else:
            # Fallback: use typical LSST variance estimates
            typical_variances = torch.tensor([0.099, 0.138, 0.354, 1.344])
            typical_variances = typical_variances[: images_tensor.shape[0]]
            weights = 1.0 / typical_variances

        total_weight = weights.sum()
        normalized_weights = weights / total_weight
        combined = torch.sum(images_tensor * normalized_weights.view(-1, 1, 1), dim=0)
        combined_variance = 1.0 / total_weight.item()

    elif method == "mean":
        combined = torch.mean(images_tensor, dim=0)
        combined_variance = 0.354  # Default

    else:
        raise ValueError(f"Unknown combination method: {method}")

    return combined, combined_variance


def combine_multiband_masks(masks_dict, method="union"):
    """
    Combine masks from multiple bands into a single mask.

    Parameters
    ----------
    masks_dict : dict
        Per-band mask arrays
    method : str
        'union': Flag pixel if bad in ANY band (recommended)
        'first_only': Use only first band's mask
        'intersection': Flag pixel only if bad in ALL bands

    Returns
    -------
    combined_mask : np.ndarray or None
    """
    if not masks_dict:
        return None

    band_names = list(masks_dict.keys())
    first_mask = masks_dict[band_names[0]]

    if method == "union":
        combined_mask = np.zeros_like(first_mask, dtype=np.int16)
        for band, mask in masks_dict.items():
            combined_mask = np.logical_or(combined_mask, mask).astype(np.int16)

    elif method == "first_only":
        combined_mask = first_mask.copy()

    elif method == "intersection":
        combined_mask = np.ones_like(first_mask, dtype=np.int16)
        for band, mask in masks_dict.items():
            combined_mask = np.logical_and(combined_mask, mask).astype(np.int16)

    else:
        raise ValueError(f"Unknown combination method: {method}")

    return combined_mask


# =============================================================================
# AnaCal Processing Functions
# =============================================================================


def anacal_single_image(
    image,
    psf_input,
    mask_array=None,
    star_catalog=None,
    npix=64,
    sigma_arcsec=0.52,
    mag_zero=30.0,
    pixel_scale=0.2,
    noise_variance=0.354,
):
    """
    Process a single-band image with anacal.

    Parameters
    ----------
    image : torch.Tensor
        Image tensor [1, H, W] or [H, W]
    psf_input : np.ndarray or GalSimPsfWrapper
        PSF image or wrapper object
    mask_array : np.ndarray or None
        Pixel mask for the band
    star_catalog : np.ndarray or None
        Bright star catalog for masking
    npix : int
        PSF cutout size
    sigma_arcsec : float
        Gaussian smoothing sigma
    mag_zero : float
        Zero point magnitude
    pixel_scale : float
        Arcsec per pixel
    noise_variance : float
        Noise variance estimate

    Returns
    -------
    e1_sum, e1g1_sum, e2_sum, e2g2_sum, num_detections
    """
    fpfs_config = anacal.fpfs.FpfsConfig(
        npix=npix,
        sigma_arcsec=sigma_arcsec,
    )

    # Handle different input shapes
    if isinstance(image, torch.Tensor):
        if len(image.shape) == 3:
            if image.shape[0] == 1:
                gal_array = image[0].numpy()
            else:
                raise ValueError(f"Expected single-band image, got {image.shape[0]} bands")
        elif len(image.shape) == 2:
            gal_array = image.numpy()
        else:
            raise ValueError(f"Unexpected image shape: {image.shape}")
    else:
        gal_array = np.asarray(image)

    noise_array = np.random.normal(0, np.sqrt(noise_variance), gal_array.shape).astype(np.float64)

    # Handle PSF
    if isinstance(psf_input, np.ndarray):
        out = anacal.fpfs.process_image(
            fpfs_config=fpfs_config,
            mag_zero=mag_zero,
            gal_array=gal_array,
            psf_array=psf_input,
            pixel_scale=pixel_scale,
            noise_variance=noise_variance,
            noise_array=noise_array,
            mask_array=mask_array,
            star_catalog=star_catalog,
            detection=None,
        )
    else:
        center_psf = psf_input.draw(gal_array.shape[1] // 2, gal_array.shape[0] // 2)
        out = anacal.fpfs.process_image(
            fpfs_config=fpfs_config,
            mag_zero=mag_zero,
            gal_array=gal_array,
            psf_array=center_psf,
            psf_object=psf_input,
            pixel_scale=pixel_scale,
            noise_variance=noise_variance,
            noise_array=noise_array,
            mask_array=mask_array,
            star_catalog=star_catalog,
            detection=None,
        )

    # Extract results
    e1 = out["fpfs_w"] * out["fpfs_e1"]
    e1g1 = out["fpfs_dw_dg1"] * out["fpfs_e1"] + out["fpfs_w"] * out["fpfs_de1_dg1"]
    e1_sum = np.sum(e1)
    e1g1_sum = np.sum(e1g1)

    e2 = out["fpfs_w"] * out["fpfs_e2"]
    e2g2 = out["fpfs_dw_dg2"] * out["fpfs_e2"] + out["fpfs_w"] * out["fpfs_de2_dg2"]
    e2_sum = np.sum(e2)
    e2g2_sum = np.sum(e2g2)

    num_detections = len(e1)

    return e1_sum, e1g1_sum, e2_sum, e2g2_sum, num_detections


def anacal_multiband_combined(
    images_tensor,
    psf_input,
    masks_dict=None,
    combine_method="inverse_variance",
    mask_combine_method="union",
    star_catalog=None,
    npix=64,
    sigma_arcsec=0.52,
    mag_zero=30.0,
    pixel_scale=0.2,
    band_variances=None,
):
    """
    Process multi-band images by combining them first, then running anacal.

    Parameters
    ----------
    images_tensor : torch.Tensor
        Shape: [n_bands, height, width]
    psf_input : np.ndarray or GalSimPsfWrapper
        PSF image or wrapper
    masks_dict : dict or None
        Per-band mask arrays
    combine_method : str
        Method for combining bands
    mask_combine_method : str
        Method for combining masks
    star_catalog : np.ndarray or None
        Bright star catalog for masking
    npix : int
        PSF cutout size
    sigma_arcsec : float
        Gaussian smoothing sigma
    mag_zero : float
        Zero point magnitude
    pixel_scale : float
        Arcsec per pixel
    band_variances : dict or None
        Per-band variance estimates

    Returns
    -------
    e1_sum, e1g1_sum, e2_sum, e2g2_sum, num_detections
    """
    # Combine images with proper inverse-variance weighting
    combined_image, combined_variance = combine_multiband_images(
        images_tensor, band_variances=band_variances, method=combine_method
    )
    gal_array = combined_image.numpy()

    # Combine masks
    combined_mask = None
    if masks_dict is not None:
        combined_mask = combine_multiband_masks(masks_dict, method=mask_combine_method)

    # Generate noise array with COMBINED variance
    noise_array = np.random.normal(0, np.sqrt(combined_variance), gal_array.shape).astype(
        np.float64
    )

    fpfs_config = anacal.fpfs.FpfsConfig(
        npix=npix,
        sigma_arcsec=sigma_arcsec,
    )

    if isinstance(psf_input, np.ndarray):
        out = anacal.fpfs.process_image(
            fpfs_config=fpfs_config,
            mag_zero=mag_zero,
            gal_array=gal_array,
            psf_array=psf_input,
            pixel_scale=pixel_scale,
            noise_variance=combined_variance,
            noise_array=noise_array,
            mask_array=combined_mask,
            star_catalog=star_catalog,
            detection=None,
        )
    else:
        center_psf = psf_input.draw(gal_array.shape[1] // 2, gal_array.shape[0] // 2)
        out = anacal.fpfs.process_image(
            fpfs_config=fpfs_config,
            mag_zero=mag_zero,
            gal_array=gal_array,
            psf_array=center_psf,
            psf_object=psf_input,
            pixel_scale=pixel_scale,
            noise_variance=combined_variance,
            noise_array=noise_array,
            mask_array=combined_mask,
            star_catalog=star_catalog,
            detection=None,
        )

    # Extract results
    e1 = out["fpfs_w"] * out["fpfs_e1"]
    e1g1 = out["fpfs_dw_dg1"] * out["fpfs_e1"] + out["fpfs_w"] * out["fpfs_de1_dg1"]
    e1_sum = np.sum(e1)
    e1g1_sum = np.sum(e1g1)

    e2 = out["fpfs_w"] * out["fpfs_e2"]
    e2g2 = out["fpfs_dw_dg2"] * out["fpfs_e2"] + out["fpfs_w"] * out["fpfs_de2_dg2"]
    e2_sum = np.sum(e2)
    e2g2_sum = np.sum(e2g2)

    num_detections = len(e1)

    return e1_sum, e1g1_sum, e2_sum, e2g2_sum, num_detections, out


# =============================================================================
# Data Loading Functions
# =============================================================================


def find_image_files(input_dir, pattern="dataset_*_size_1.pt"):
    """Find all image files in the input directory."""
    files = sorted(glob.glob(os.path.join(input_dir, pattern)))
    return files


def extract_index_from_filename(filename):
    """Extract the image index from filename like 'dataset_123_size_1.pt'."""
    basename = os.path.basename(filename)
    # Format: dataset_{idx}_size_1.pt
    parts = basename.replace(".pt", "").split("_")
    try:
        return int(parts[1])
    except (IndexError, ValueError):
        return -1


def load_image_data(file_path):
    """Load image data from a .pt file."""
    data_list = torch.load(file_path, weights_only=False)
    return data_list[0]  # First element of the list


# =============================================================================
# Processing Functions
# =============================================================================


def process_single_file(file_path, config):
    """
    Process a single image file with AnaCal.

    Parameters
    ----------
    file_path : str
        Path to the .pt file
    config : dict
        AnaCal configuration

    Returns
    -------
    dict with results or None if processing failed
    """
    try:
        data = load_image_data(file_path)
        images = data["images"]
        catalog = data["tile_catalog"]
        anacal_data = data["anacal_data"]

        n_bands = images.shape[0]

        # Get AnaCal inputs
        psf_image = anacal_data["psf_image"]
        masks_dict = anacal_data["masks"]
        band_variances = anacal_data["variances"]
        bright_star_catalog = anacal_data.get("bright_star_catalog")
        pixel_scale = anacal_data.get("pixel_scale", config["pixel_scale"])

        # Process based on band count
        if n_bands == 1:
            # Single-band processing
            band = next(iter(masks_dict.keys()))
            single_band_mask = masks_dict.get(band)
            single_band_variance = band_variances.get(band, 0.354)

            e1_sum, e1g1_sum, e2_sum, e2g2_sum, num_detections = anacal_single_image(
                images,
                psf_image,
                mask_array=single_band_mask,
                star_catalog=bright_star_catalog,
                npix=config["npix"],
                sigma_arcsec=config["sigma_arcsec"],
                mag_zero=config["mag_zero"],
                pixel_scale=pixel_scale,
                noise_variance=single_band_variance,
            )
        else:
            # Multi-band processing
            e1_sum, e1g1_sum, e2_sum, e2g2_sum, num_detections, _ = anacal_multiband_combined(
                images,
                psf_image,
                masks_dict=masks_dict,
                combine_method=config["combine_method"],
                mask_combine_method=config["mask_combine_method"],
                star_catalog=bright_star_catalog,
                npix=config["npix"],
                sigma_arcsec=config["sigma_arcsec"],
                mag_zero=config["mag_zero"],
                pixel_scale=pixel_scale,
                band_variances=band_variances,
            )

        return {
            "e1_sum": float(e1_sum),
            "e1g1_sum": float(e1g1_sum),
            "e2_sum": float(e2_sum),
            "e2g2_sum": float(e2g2_sum),
            "num_detections": int(num_detections),
            "shear_1": float(catalog["shear_1"]),
            "shear_2": float(catalog["shear_2"]),
            "index": extract_index_from_filename(file_path),
        }

    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None


def process_single_file_worker(args):
    """Worker function for multiprocessing - unpacks args tuple."""
    file_path, config = args
    return process_single_file(file_path, config)


def save_checkpoint(results, output_file, is_final=False):
    """Save current results to a checkpoint file."""
    if is_final:
        checkpoint_path = output_file
    else:
        # Create checkpoint path by adding .checkpoint before .pt
        base, ext = os.path.splitext(output_file)
        checkpoint_path = f"{base}_checkpoint{ext}"

    # Convert lists to numpy arrays
    output = {
        "e1_sum": np.array(results["e1_sum"]),
        "e1g1_sum": np.array(results["e1g1_sum"]),
        "e2_sum": np.array(results["e2_sum"]),
        "e2g2_sum": np.array(results["e2g2_sum"]),
        "num_detections": np.array(results["num_detections"]),
        "shear_1": np.array(results["shear_1"]),
        "shear_2": np.array(results["shear_2"]),
        "indices": np.array(results["indices"]),
        # Aggregated statistics
        "total_e1_sum": float(np.sum(results["e1_sum"])),
        "total_e1g1_sum": float(np.sum(results["e1g1_sum"])),
        "total_e2_sum": float(np.sum(results["e2_sum"])),
        "total_e2g2_sum": float(np.sum(results["e2g2_sum"])),
        "total_detections": int(np.sum(results["num_detections"])),
        # Metadata
        "n_images_processed": len(results["e1_sum"]),
        "config": results.get("config", {}),
        "timestamp": datetime.now().isoformat(),
    }

    torch.save(output, checkpoint_path)
    return checkpoint_path


def process_all_images(
    input_dir,
    output_file,
    config,
    start_idx=0,
    end_idx=None,
    checkpoint_interval=50,
    n_workers=1,
    verbose=False,
):
    """
    Process all images in the input directory.

    Parameters
    ----------
    input_dir : str
        Directory containing dataset_*.pt files
    output_file : str
        Path for output results file
    config : dict
        AnaCal configuration
    start_idx : int
        Start processing from this index
    end_idx : int or None
        End processing at this index (None = all files)
    checkpoint_interval : int
        Save checkpoint every N images
    n_workers : int
        Number of parallel workers (1 = sequential)
    verbose : bool
        Print detailed progress

    Returns
    -------
    dict with accumulated results
    """
    # Find all image files
    files = find_image_files(input_dir)
    print(f"Found {len(files)} image files in {input_dir}")

    if len(files) == 0:
        print("No files to process!")
        return None

    # Apply start/end indices
    files = files[start_idx:end_idx] if end_idx is not None else files[start_idx:]

    print(f"Processing {len(files)} files (indices {start_idx} to {start_idx + len(files) - 1})")
    print(f"Workers: {n_workers}")

    # Initialize result accumulators
    results = {
        "e1_sum": [],
        "e1g1_sum": [],
        "e2_sum": [],
        "e2g2_sum": [],
        "num_detections": [],
        "shear_1": [],
        "shear_2": [],
        "indices": [],
        "config": config,
    }

    start_time = time.time()
    failed_count = 0
    processed_count = 0

    def append_result(result):
        """Helper to append a single result to accumulator."""
        results["e1_sum"].append(result["e1_sum"])
        results["e1g1_sum"].append(result["e1g1_sum"])
        results["e2_sum"].append(result["e2_sum"])
        results["e2g2_sum"].append(result["e2g2_sum"])
        results["num_detections"].append(result["num_detections"])
        results["shear_1"].append(result["shear_1"])
        results["shear_2"].append(result["shear_2"])
        results["indices"].append(result["index"])

    if n_workers <= 1:
        # Sequential processing
        for i, file_path in enumerate(tqdm(files, desc="Processing", unit="img")):
            result = process_single_file(file_path, config)

            if result is not None:
                append_result(result)
                processed_count += 1
            else:
                failed_count += 1

            # Save checkpoint periodically
            if checkpoint_interval > 0 and (i + 1) % checkpoint_interval == 0:
                checkpoint_path = save_checkpoint(results, output_file, is_final=False)
                if verbose:
                    print(f"\nCheckpoint saved after {i + 1} images: {checkpoint_path}")
    else:
        # Parallel processing with multiprocessing
        args_list = [(f, config) for f in files]

        with ProcessPoolExecutor(max_workers=n_workers) as executor:
            # Submit all tasks
            future_to_file = {
                executor.submit(process_single_file_worker, args): args[0] for args in args_list
            }

            # Process results as they complete
            for future in tqdm(
                as_completed(future_to_file), total=len(files), desc="Processing", unit="img"
            ):
                file_path = future_to_file[future]
                try:
                    result = future.result()
                    if result is not None:
                        append_result(result)
                        processed_count += 1
                    else:
                        failed_count += 1
                except Exception as e:
                    print(f"\nError processing {file_path}: {e}")
                    failed_count += 1

                # Save checkpoint periodically
                if checkpoint_interval > 0 and processed_count % checkpoint_interval == 0:
                    checkpoint_path = save_checkpoint(results, output_file, is_final=False)
                    if verbose:
                        print(
                            f"\nCheckpoint saved after {processed_count} images: {checkpoint_path}"
                        )

    # Save final results
    elapsed_time = time.time() - start_time
    results["processing_time"] = elapsed_time

    final_path = save_checkpoint(results, output_file, is_final=True)
    print(f"\nFinal results saved to: {final_path}")

    # Remove checkpoint file if it exists
    base, ext = os.path.splitext(output_file)
    checkpoint_path = f"{base}_checkpoint{ext}"
    if os.path.exists(checkpoint_path):
        os.remove(checkpoint_path)
        print(f"Removed checkpoint file: {checkpoint_path}")

    # Print summary
    n_processed = len(results["e1_sum"])
    print("\n=== PROCESSING COMPLETE ===")
    print(f"Successfully processed: {n_processed}/{len(files)} images")
    if failed_count > 0:
        print(f"Failed: {failed_count} files")
    print(f"Total time: {elapsed_time:.2f} seconds")
    print(f"Average time per image: {elapsed_time / max(n_processed, 1):.3f} seconds")
    if n_workers > 1:
        print(f"Effective throughput: {n_processed / elapsed_time:.2f} img/sec")
    print(f"Total detections: {np.sum(results['num_detections'])}")

    return results


# =============================================================================
# Main Entry Point
# =============================================================================


def main():
    # Determine config file path
    if len(sys.argv) > 1:
        config_file = sys.argv[1]
    else:
        # Default to config_anacal.yaml in same directory as script
        script_dir = os.path.dirname(os.path.abspath(__file__))
        config_file = os.path.join(script_dir, "config_anacal.yaml")

    if not os.path.exists(config_file):
        print(f"Error: Config file not found: {config_file}")
        print("Usage: python run_anacal.py config_anacal.yaml")
        sys.exit(1)

    start_datetime = datetime.now()
    print("=== ANACAL PROCESSING ===")
    print(f"Start time: {start_datetime.strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 50)

    # Load config from YAML
    print(f"Loading config from: {config_file}")
    with open(config_file) as f:
        user_config = yaml.safe_load(f)

    # Merge with defaults for AnaCal parameters
    config = DEFAULT_CONFIG.copy()
    config.update(user_config)

    # Extract required paths
    input_dir = config.get("input_dir")
    output_file = config.get("output_file")

    if not input_dir or not output_file:
        print("Error: config must specify 'input_dir' and 'output_file'")
        sys.exit(1)

    # Extract optional settings with defaults
    start_idx = config.get("start_idx", 0)
    end_idx = config.get("end_idx")  # None = all files
    checkpoint_interval = config.get("checkpoint_interval", 50)
    n_workers = config.get("n_workers", 1)
    verbose = config.get("verbose", False)

    print("Configuration:")
    for key, value in config.items():
        print(f"  {key}: {value}")

    # Ensure output directory exists
    output_dir = os.path.dirname(output_file)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Run processing
    process_all_images(
        input_dir=input_dir,
        output_file=output_file,
        config=config,
        start_idx=start_idx,
        end_idx=end_idx,
        checkpoint_interval=checkpoint_interval,
        n_workers=n_workers,
        verbose=verbose,
    )

    print(f"\nEnd time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 50)


if __name__ == "__main__":
    main()
