---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

mode: train

dc2_min_flux: 0.0
dc2_min_log_flux: 0.0
dc2_max_log_flux: 23.43
dc2_min_ellipticity: -0.93
dc2_max_ellipticity: 0.93

surveys:
  dc2:
    batch_size: 128

my_factors:
  - _target_: case_studies.dc2_other.utils.catalog_parser.OneBitFactor
    n_params: 1
    name: n_sources
    bit_value: 0.8
    sample_rearrange: b ht wt 1 -> b ht wt
    loss_gating: null
  - _target_: case_studies.dc2_other.utils.catalog_parser.OneBitFactor
    n_params: 1
    name: source_type
    bit_value: 0.8
    sample_rearrange: b ht wt 1 -> b ht wt 1 1
    loss_gating:
      _target_: case_studies.dc2_other.utils.catalog_parser.SourcesGating
  - _target_: case_studies.dc2_other.utils.catalog_parser.NormalizedFactor
    n_params: 2
    name: locs
    data_min: 0.0
    data_max: 1.0
    sample_rearrange: b ht wt d -> b ht wt 1 d
    loss_gating:
      _target_: case_studies.dc2_other.utils.catalog_parser.SourcesGating
  - _target_: case_studies.dc2_other.utils.catalog_parser.LogNormalizedFactor
    n_params: 6
    name: fluxes
    data_min: ${dc2_min_flux}
    log_data_min: ${dc2_min_log_flux}
    log_data_max: ${dc2_max_log_flux}
    sample_rearrange: b ht wt d -> b ht wt 1 d
    loss_gating:
      _target_: case_studies.dc2_other.utils.catalog_parser.SourcesGating

my_metrics:
  detection_performance:
    _target_: bliss.encoder.metrics.DetectionPerformance
    base_flux_bin_cutoffs: [200, 400, 600, 800, 1000]
    mag_zero_point: 3631e9  # for DC2
    report_bin_unit: mag
  detection_performance_star:
    _target_: bliss.encoder.metrics.DetectionPerformance
    base_flux_bin_cutoffs: [200, 400, 600, 800, 1000]
    mag_zero_point: 3631e9  # for DC2
    report_bin_unit: mag
    filter_list:
      - _target_: bliss.encoder.metrics.SourceTypeFilter
        filter_type: star
  detection_performance_galaxy:
    _target_: bliss.encoder.metrics.DetectionPerformance
    base_flux_bin_cutoffs: [200, 400, 600, 800, 1000]
    mag_zero_point: 3631e9  # for DC2
    report_bin_unit: mag
    filter_list:
      - _target_: bliss.encoder.metrics.SourceTypeFilter
        filter_type: galaxy
  source_type_accuracy:
    _target_: bliss.encoder.metrics.SourceTypeAccuracy
    base_flux_bin_cutoffs: [200, 400, 600, 800, 1000]
    mag_zero_point: 3631e9  # for DC2
    report_bin_unit: mag
  flux_error:
    _target_: bliss.encoder.metrics.FluxError
    survey_bands: ${encoder.survey_bands}
    base_flux_bin_cutoffs: [200, 400, 600, 800, 1000]
    mag_zero_point: 3631e9  # for DC2
    report_bin_unit: mag

my_image_normalizers:
  null_noramlize:
      _target_: case_studies.dc2_cataloging.utils.image_normalizer.NullNormalizer

encoder:
    _target_: case_studies.dc2_other.utils.encoder.MyEncoder
    survey_bands: [u, g, r, i, z, y]
    reference_band: 2
    tile_slen: ${surveys.dc2.tile_slen}
    optimizer_params:
        lr: 1e-3
    scheduler_params:
        milestones: [32]
        gamma: 0.1
    image_normalizers: ${my_image_normalizers}
    catalog_parser:
        _target_: case_studies.dc2_other.utils.catalog_parser.CatalogParser
        factors: ${my_factors}
    image_size: [80, 80]
    matcher:
        _target_: bliss.encoder.metrics.CatalogMatcher
        dist_slack: 1.0
        mag_slack: null
        mag_band: 2  # SDSS r-band
    mode_metrics:
        _target_: torchmetrics.MetricCollection
        _convert_: partial
        compute_groups: false
        metrics: ${my_metrics}

train:
    trainer:
        logger:
            name: DC2_other_exp
            version: exp_01-06-6  # change it before running the code
        devices: [3]  # change it before running the code
        use_distributed_sampler: false  # disable this because we use the self-defined distributed sampler
        precision: 32-true
    data_source: ${surveys.dc2}
    pretrained_weights: null
    seed: 7272
