defaults:
    - ./@_here_: config
    - _self_
    - override hydra/job_logging: stdout

paths:
    cached_data: /data/scratch/aakash/multi_field_train

encoder:
    image_normalizers: ${psf_asinh_normalizers}
    var_dist:
        _target_: bliss.encoder.variational_dist.VariationalDist
        tile_slen: ${encoder.tile_slen}
        factors: ${no_gal_shape_variational_factors}

train:
    trainer:
        logger:
            name: PSF_MODELS
            version: psf_aware
