---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    root: ${oc.env:BLISS_HOME}
    data: ${paths.root}/data
    sdss: ${paths.data}/sdss
    output: ${paths.root}/redshift_output

prior:
    _target_: case_studies.redshift_estimation.prior.RedshiftCSVPrior
    redshift_min: 0.99
    redshift_max: 1.01

simulator:
    _target_: case_studies.redshift_estimation.simulated_dataset.RedshiftSimulatedDataset

encoder:
    vd_spec:
        _target_: case_studies.redshift_estimation.variational_dist.RedshiftVariationalDistSpec
    double_detect: false
    use_checkerboard: false

generate:
    n_image_files: 16
    n_batches_per_file: 16
    cached_data_path: /data/scratch/yolandz/star_test

cached_simulator:
    cached_data_path: /data/scratch/declan/redshift_estimation_test
    batch_size: 32
