---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

prior:
    _target_: case_studies.redshift_estimation.prior_truth.RedshiftPrior

simulator:
    _target_: case_studies.redshift_estimation.simulated_dataset_truth.RedshiftSimulatedDataset

encoder:
    vd_spec:
        _target_: case_studies.redshift_estimation.variational_dist.RedshiftVariationalDistSpec
