---
defaults:
    - ../../bliss/conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    root: ${oc.env:BLISS_HOME}
    data: ${paths.root}/data
    sdss: ${paths.data}/sdss
    output: ${paths.root}/redshift_output

prior:
    _target_: case_studies.redshift_estimation.prior.RedshiftCSVPriorDC2

simulator:
    _target_: case_studies.redshift_estimation.simulated_dataset.RedshiftSimulatedDataset

encoder:
    vd_spec:
        _target_: case_studies.redshift_estimation.variational_dist.RedshiftVariationalDistSpec
    double_detect: false
    use_checkerboard: false
    optimizer_params:
        lr: 1e-4
    metrics:
        _target_: torchmetrics.MetricCollection
        metrics:
          - _target_: bliss.encoder.metrics.DetectionPerformance
            mag_bin_cutoffs: [19, 19.4, 19.8, 20.2, 20.6, 21, 21.4, 21.8]
          - _target_: bliss.encoder.metrics.SourceTypeAccuracy
          - _target_: bliss.encoder.metrics.FluxError
            survey_bands: ${encoder.survey_bands}
          - _target_: bliss.encoder.metrics.GalaxyShapeError
          - _target_: case_studies.redshift_estimation.metrics.RedshiftMeanSquaredError
    marginal_metrics:
        _target_: torchmetrics.MetricCollection
        metrics:
          - _target_: case_studies.redshift_estimation.metrics.RedshiftNLL

generate:
    n_image_files: 16
    n_batches_per_file: 16
    cached_data_path: /data/scratch/declan/sdss_like_stars_test

cached_simulator:
    _target_: case_studies.redshift_estimation.simulated_dataset.RedshiftCachedSimulatedDataset
    cached_data_path: /data/scratch/declan/sdss_like_stars_test
    batch_size: 32

cached_test_data:
    _target_: case_studies.redshift_estimation.simulated_dataset.RedshiftCachedSimulatedDataset
    batch_size: 32
    splits: 0:80/80:90/90:100  # train/val/test splits as percent ranges
    num_workers: 0
    file_prefix: ${generate.file_prefix}
    cached_data_path: /data/scratch/declan/redshift_estimation_test

predict:
    dataset: ${cached_test_data}
