---
defaults:
    - ../../conf@_here_: base_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    project: ${paths.root}/case_studies/721_decoder_speedup
    output: ${paths.project}/output
    pretrained_models: ${paths.data}/pretrained_models

simulator:
    background:
        _target_: bliss.simulator.background.SimulatedSDSSBackground
        sdss_dir: ${paths.sdss}
        run: 94
        camcol: 1
        field: 12
        bands: [2]

training:
    name: "sdss_encoder"
    testing:
        num_workers: 0  # why not increase this?
    weight_save_path: ${paths.output}/${training.name}/${training.version}.pt
    seed: 42
    use_cached_simulator: true
