# @package _global_
training:
    name: "sdss_galaxy_encoder"
    model: ${models.galaxy_encoder}
    dataset: ${datasets.simulated}
    n_epochs: 10001
    trainer:
        enable_checkpointing: True
        check_val_every_n_epoch: 100
