# @package _global_
training:
  name: "sdss_detection_encoder"
  model: ${models.detection_encoder}
  dataset: ${datasets.simulated}
  n_epochs: 3001
  save_top_k: 10
  trainer:
    enable_checkpointing: True
