# @package _global_
models:
    prior:
        mean_sources: 0.04

training:
    name: "sdss_galaxy_encoder"
    model: ${models.galaxy_encoder}
    dataset: ${datasets.simulated}
    n_epochs: 4001
    trainer:
        enable_checkpointing: True
        check_val_every_n_epoch: 50
