---
defaults:
    - m2_mdt_rml_train_config
    - _self_
    - override hydra/job_logging: stdout

train:
    trainer:
        logger:
            name: M2_mdt_debug
            version: M2_mdt_debug
        devices: [6, 7]
