---
defaults:
    - m2_simple_net_train_config
    - _self_
    - override hydra/job_logging: stdout

paths:
    cached_data: /tmpssd/pduan/m2_aug30
    output: /home/pduan/bliss_output

cached_simulator:
    batch_size: 256
    num_workers: 8

train:
    trainer:
        logger:
            version: null  # override this in command line
        devices: null  # override this in command line
        precision: 32-true
    matmul_precision: high
